//! Asset cleanup registry.
//!
//! Cleanup functions are submitted via `inventory::submit!()`.
//! During scene transitions / hot reload, `clear_all_programmatic_assets()`
//! iterates all registered cleaners.

use bevy::ecs::world::World;

/// A registered asset cleanup function collected via `inventory`.
///
/// Each asset type submits one of these (generated by the `#[pyasset]` macro).
/// The `clear` function removes programmatic assets (those without an
/// AssetServer path) from the world.
pub struct AssetCleanupRegistration {
    /// Function that clears programmatic assets of one type from the world.
    pub clear: fn(&mut World, bool),
    /// Human-readable name for verbose logging.
    pub name: &'static str,
}

inventory::collect!(AssetCleanupRegistration);

/// Clear programmatic assets for all registered types.
///
/// Iterates all `AssetCleanupRegistration` entries submitted via `inventory`
/// and calls each cleaner. File-loaded assets are preserved.
pub fn clear_all_programmatic_assets(world: &mut World, verbose: bool) {
    for reg in inventory::iter::<AssetCleanupRegistration> {
        (reg.clear)(world, verbose);
    }
}
