[package]
name = "pybevy_ecs"
version = "0.2.1"
edition = "2024"
description = "ECS components for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_storage = { path = "../pybevy_storage", version = "=0.2.1" }

[dependencies.bevy]
workspace = true
features = []
