[package]
name = "pybevy_sprite"
version = "0.2.0"
edition = "2024"
description = "Sprite components for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_color = { workspace = true }
pybevy_image = { workspace = true }
pybevy_math = { workspace = true }
pybevy_macros = { workspace = true }
numpy = { workspace = true }

[dependencies.bevy]
workspace = true
features = ["bevy_sprite", "bevy_sprite_render", "bevy_camera"]
