[package]
name = "pybevy_math"
version = "0.3.0"
edition = "2024"
description = "Math types (Vec2, Vec3, Vec4, Quat, Mat3, Mat4) for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }

[dependencies.bevy]
workspace = true

[dependencies.bevy_math]
version = "0.19.1"
features = ["curve"]
default-features = false

[lints]
workspace = true
