[package]
name = "pybevy_macros"
version = "0.2.1"
edition = "2024"
description = "Procedural macros for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "3"

[lints]
workspace = true
