pub mod aabb;
pub mod camera;
pub mod camera_3d;
pub mod camera_3d_depth_load_op;
pub mod camera_3d_depth_texture_usage;
pub mod camera_main_texture_usages;
pub mod clear_color;
pub mod clear_color_config;
pub mod cubemap_frusta;
pub mod cubemap_layout;
pub mod cubemap_visible_entities;
pub mod culling_sphere;
pub mod exposure;
pub mod frustum;
pub mod half_space;
pub mod inherited_visibility;
pub mod main_pass_resolution_override;
pub mod normalized_render_target;
pub mod physical_camera_parameters;
pub mod plugin;
pub mod projection;
pub mod render_layers;
pub mod render_target;
pub mod screen_space_transmission_quality;
pub mod skybox;
pub mod sub_camera_view;
pub mod unit_markers;
pub mod view_visibility;
pub mod viewport;
pub mod visibility;
pub mod visibility_batch;
pub mod visibility_class;
pub mod visibility_range;
pub mod visible_mesh_entities;

pub use aabb::PyAabb;
pub use camera::PyCamera;
pub use camera_3d::PyCamera3d;
pub use camera_3d_depth_load_op::PyCamera3dDepthLoadOp;
pub use camera_3d_depth_texture_usage::PyCamera3dDepthTextureUsage;
pub use camera_main_texture_usages::PyCameraMainTextureUsages;
pub use clear_color::PyClearColor;
pub use clear_color_config::PyClearColorConfig;
pub use cubemap_frusta::PyCubemapFrusta;
pub use cubemap_layout::PyCubemapLayout;
pub use cubemap_visible_entities::PyCubemapVisibleEntities;
pub use culling_sphere::PyCullingSphere;
pub use exposure::PyExposure;
pub use frustum::PyFrustum;
pub use half_space::PyHalfSpace;
pub use inherited_visibility::PyInheritedVisibility;
pub use main_pass_resolution_override::PyMainPassResolutionOverride;
pub use normalized_render_target::PyNormalizedRenderTarget;
pub use physical_camera_parameters::PyPhysicalCameraParameters;
pub use plugin::PyCameraPlugin;
pub use projection::{PyOrthographicProjection, PyPerspectiveProjection, PyProjection};
pub mod scaling_mode;
use pyo3::prelude::*;
pub use render_layers::PyRenderLayers;
pub use render_target::PyRenderTarget;
pub use scaling_mode::PyScalingMode;
pub use screen_space_transmission_quality::PyScreenSpaceTransmissionQuality;
pub use skybox::PySkybox;
pub use sub_camera_view::PySubCameraView;
pub use unit_markers::{
    PyCamera2d, PyDeferredPrepass, PyDepthPrepass, PyMotionVectorPrepass, PyNoCpuCulling,
    PyNoFrustumCulling, PyNormalPrepass,
};
pub use view_visibility::PyViewVisibility;
pub use viewport::PyViewport;
pub use visibility::PyVisibility;
pub use visibility_class::PyVisibilityClass;
pub use visibility_range::PyVisibilityRange;
pub use visible_mesh_entities::PyVisibleMeshEntities;

pub fn add_module(parent: &Bound<'_, PyModule>) -> PyResult<()> {
    visibility_batch::register_visibility_batch_bridge();

    let m = PyModule::new(parent.py(), "camera")?;
    m.add_class::<PyCameraPlugin>()?;
    m.add_class::<PyNoCpuCulling>()?;
    m.add_class::<PyNoFrustumCulling>()?;
    m.add_class::<PyCamera2d>()?;
    m.add_class::<PyDepthPrepass>()?;
    m.add_class::<PyNormalPrepass>()?;
    m.add_class::<PyMotionVectorPrepass>()?;
    m.add_class::<PyDeferredPrepass>()?;
    m.add_class::<PyCamera>()?;
    m.add_class::<PyCamera3d>()?;
    m.add_class::<PyInheritedVisibility>()?;
    m.add_class::<PyViewVisibility>()?;
    m.add_class::<PyVisibilityRange>()?;
    m.add_class::<PyExposure>()?;
    m.add_class::<PyRenderLayers>()?;
    m.add_class::<PyAabb>()?;
    m.add_class::<PyCubemapFrusta>()?;
    m.add_class::<PyCubemapVisibleEntities>()?;
    m.add_class::<PyFrustum>()?;
    m.add_class::<PyProjection>()?;
    m.add_class::<PyVisibility>()?;
    m.add_class::<visibility_batch::PyVisibilityBatch>()?;
    m.add_class::<PyVisibilityClass>()?;
    m.add_class::<PyVisibleMeshEntities>()?;
    m.add_class::<PySkybox>()?;
    m.add_class::<PyRenderTarget>()?;
    m.add_class::<PyNormalizedRenderTarget>()?;
    m.add_class::<PyPhysicalCameraParameters>()?;
    m.add_class::<PyHalfSpace>()?;
    m.add_class::<PyCullingSphere>()?;
    m.add_class::<PyScalingMode>()?;
    m.add_class::<PyCubemapLayout>()?;
    m.add_class::<PyScreenSpaceTransmissionQuality>()?;
    m.add_class::<PyCamera3dDepthLoadOp>()?;
    m.add_class::<PyCamera3dDepthTextureUsage>()?;
    m.add_class::<PyClearColorConfig>()?;
    m.add_class::<PySubCameraView>()?;
    m.add_class::<PyPerspectiveProjection>()?;
    m.add_class::<PyOrthographicProjection>()?;
    m.add_class::<PyCameraMainTextureUsages>()?;
    m.add_class::<PyMainPassResolutionOverride>()?;
    m.add_class::<PyViewport>()?;
    m.add_class::<PyClearColor>()?;
    parent.add_submodule(&m)
}
