[package]
name = "pybevy_input"
version = "0.3.0"
edition = "2024"
description = "Input components for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_math = { workspace = true }

[dependencies.bevy]
workspace = true
features = ["mouse", "keyboard", "gamepad", "touch", "gestures"]

[lints]
workspace = true
