[package]
name = "pybevy_input"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_math = { workspace = true }

[dependencies.bevy]
workspace = true
features = []
