"""Accessibility plugin for PyBevy."""

from enum import Enum

from pybevy.app import App, Plugin
from pybevy.ecs import Component

class Role(Enum):
    """Accessibility role for UI elements."""

    # Common interactive elements
    Unknown = ...
    TextRun = ...
    Cell = ...
    Label = ...
    Image = ...
    Link = ...
    Row = ...
    ListItem = ...
    ListMarker = ...
    TreeItem = ...
    ListBoxOption = ...
    MenuItem = ...
    MenuListOption = ...
    Paragraph = ...
    GenericContainer = ...
    CheckBox = ...
    RadioButton = ...
    TextInput = ...
    Button = ...
    DefaultButton = ...
    Pane = ...
    RowHeader = ...
    ColumnHeader = ...
    RowGroup = ...
    List = ...
    Table = ...
    LayoutTableCell = ...
    LayoutTableRow = ...
    LayoutTable = ...
    Switch = ...
    Menu = ...
    MultilineTextInput = ...
    SearchInput = ...
    DateInput = ...
    DateTimeInput = ...
    WeekInput = ...
    MonthInput = ...
    TimeInput = ...
    EmailInput = ...
    NumberInput = ...
    PasswordInput = ...
    PhoneNumberInput = ...
    UrlInput = ...
    Abbr = ...
    Alert = ...
    AlertDialog = ...
    Application = ...
    Article = ...
    Audio = ...
    Banner = ...
    Blockquote = ...
    Canvas = ...
    Caption = ...
    Caret = ...
    Code = ...
    ColorWell = ...
    ComboBox = ...
    EditableComboBox = ...
    Complementary = ...
    Comment = ...
    ContentDeletion = ...
    ContentInsertion = ...
    ContentInfo = ...
    Definition = ...
    DescriptionList = ...
    Details = ...
    Dialog = ...
    DisclosureTriangle = ...
    Document = ...
    EmbeddedObject = ...
    Emphasis = ...
    Feed = ...
    FigureCaption = ...
    Figure = ...
    Footer = ...
    Form = ...
    Grid = ...
    GridCell = ...
    Group = ...
    Header = ...
    Heading = ...
    Iframe = ...
    IframePresentational = ...
    ImeCandidate = ...
    Keyboard = ...
    Legend = ...
    LineBreak = ...
    ListBox = ...
    Log = ...
    Main = ...
    Mark = ...
    Marquee = ...
    Math = ...
    MenuBar = ...
    MenuItemCheckBox = ...
    MenuItemRadio = ...
    MenuListPopup = ...
    Meter = ...
    Navigation = ...
    Note = ...
    PluginObject = ...
    ProgressIndicator = ...
    RadioGroup = ...
    Region = ...
    RootWebArea = ...
    Ruby = ...
    RubyAnnotation = ...
    ScrollBar = ...
    ScrollView = ...
    Search = ...
    Section = ...
    SectionFooter = ...
    SectionHeader = ...
    Slider = ...
    SpinButton = ...
    Splitter = ...
    Status = ...
    Strong = ...
    Suggestion = ...
    SvgRoot = ...
    Tab = ...
    TabList = ...
    TabPanel = ...
    Term = ...
    Time = ...
    Timer = ...
    TitleBar = ...
    Toolbar = ...
    Tooltip = ...
    Tree = ...
    TreeGrid = ...
    Video = ...
    WebView = ...
    Window = ...
    PdfActionableHighlight = ...
    PdfRoot = ...
    GraphicsDocument = ...
    GraphicsObject = ...
    GraphicsSymbol = ...
    DocAbstract = ...
    DocAcknowledgements = ...
    DocAfterword = ...
    DocAppendix = ...
    DocBackLink = ...
    DocBiblioEntry = ...
    DocBibliography = ...
    DocBiblioRef = ...
    DocChapter = ...
    DocColophon = ...
    DocConclusion = ...
    DocCover = ...
    DocCredit = ...
    DocCredits = ...
    DocDedication = ...
    DocEndnote = ...
    DocEndnotes = ...
    DocEpigraph = ...
    DocEpilogue = ...
    DocErrata = ...
    DocExample = ...
    DocFootnote = ...
    DocForeword = ...
    DocGlossary = ...
    DocGlossRef = ...
    DocIndex = ...
    DocIntroduction = ...
    DocNoteRef = ...
    DocNotice = ...
    DocPageBreak = ...
    DocPageFooter = ...
    DocPageHeader = ...
    DocPageList = ...
    DocPart = ...
    DocPreface = ...
    DocPrologue = ...
    DocPullquote = ...
    DocQna = ...
    DocSubtitle = ...
    DocTip = ...
    DocToc = ...
    ListGrid = ...
    Terminal = ...

    def __hash__(self) -> int: ...

class AccessibilityNode(Component):
    """Component for accessibility integration using AccessKit.

    Represents an entity in the accessibility tree, allowing screen readers
    and other assistive technologies to interact with UI elements.

    Example:
        ```python
        # Create an accessibility node for a button
        commands.spawn((
            Button(),
            AccessibilityNode(Role.Button),
        ))

        # Create a list item with a label
        node = AccessibilityNode(Role.ListItem)
        node.set_label("Item 1")
        commands.spawn((Text("Item 1"), node))
        ```
    """

    def __init__(self, role: Role = Role.Unknown) -> None: ...

    @property
    def role(self) -> Role:
        """The accessibility role of this node."""

    def set_role(self, role: Role) -> None:
        """Set the accessibility role."""

    @property
    def label(self) -> str | None:
        """The accessible label (name) of this node."""

    def set_label(self, label: str) -> None:
        """Set the accessible label."""

    def clear_label(self) -> None:
        """Clear the accessible label."""

    @property
    def value(self) -> str | None:
        """The current value of this node (for inputs, sliders, etc.)."""

    def set_value(self, value: str) -> None:
        """Set the current value."""

    def clear_value(self) -> None:
        """Clear the current value."""

    @property
    def description(self) -> str | None:
        """Additional descriptive text about this node."""

    def set_description(self, description: str) -> None:
        """Set the description."""

    def clear_description(self) -> None:
        """Clear the description."""

    @property
    def is_disabled(self) -> bool:
        """Whether this node is disabled."""

    def set_disabled(self, disabled: bool) -> None:
        """Set the disabled state."""

    @property
    def is_hidden(self) -> bool:
        """Whether this node is hidden from assistive technology."""

    def set_hidden(self, hidden: bool) -> None:
        """Set the hidden state."""

    @property
    def is_expanded(self) -> bool | None:
        """Whether this node is expanded (for expandable elements)."""

    def set_expanded(self, expanded: bool) -> None:
        """Set the expanded state."""

    def clear_expanded(self) -> None:
        """Clear the expanded state."""

    @property
    def is_selected(self) -> bool | None:
        """Whether this node is selected."""

    def set_selected(self, selected: bool) -> None:
        """Set the selected state."""

    def clear_selected(self) -> None:
        """Clear the selected state."""

    @property
    def numeric_value(self) -> float | None:
        """The numeric value (for sliders, progress bars, etc.)."""

    def set_numeric_value(self, value: float) -> None:
        """Set the numeric value."""

    def clear_numeric_value(self) -> None:
        """Clear the numeric value."""

    @property
    def min_numeric_value(self) -> float | None:
        """The minimum numeric value."""

    def set_min_numeric_value(self, value: float) -> None:
        """Set the minimum numeric value."""

    def clear_min_numeric_value(self) -> None:
        """Clear the minimum numeric value."""

    @property
    def max_numeric_value(self) -> float | None:
        """The maximum numeric value."""

    def set_max_numeric_value(self, value: float) -> None:
        """Set the maximum numeric value."""

    def clear_max_numeric_value(self) -> None:
        """Clear the maximum numeric value."""

    def set_bounds(
        self, min_x: float, min_y: float, max_x: float, max_y: float
    ) -> None:
        """Set the bounding rectangle for this node in screen coordinates."""

    def clear_bounds(self) -> None:
        """Clear the bounding rectangle."""

class AccessibilityPlugin(Plugin):
    """Accessibility plugin providing screen reader and accessibility support."""

    def __init__(self) -> None: ...
    def build(self, app: App) -> None: ...
