from typing import Any, Literal, overload

from pybevy.expr import Expr, FieldExpr

class dtype:
    def __init__(self, spec: object) -> None: ...
    @property
    def name(self) -> str: ...
    @overload
    def __call__(self, value: bool | int | float) -> bool | int | float: ...
    @overload
    def __call__(self, value: object) -> object: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

float16: dtype
float32: dtype
float64: dtype
int64: dtype
int32: dtype
uint32: dtype
uint16: dtype
uint8: dtype
bool_: dtype

class Array:
    def __dlpack_device__(self) -> tuple[Literal[1], Literal[0]]: ...
    def __dlpack__(
        self,
        *,
        stream: int | None = None,
        max_version: tuple[int, int] | None = None,
        dl_device: tuple[int, int] | None = None,
        copy: bool | None = None,
    ) -> object: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dtype(self) -> dtype: ...
    @property
    def ndim(self) -> int: ...
    @property
    def size(self) -> int: ...
    @property
    def itemsize(self) -> int: ...
    @property
    def strides(self) -> tuple[int, ...]: ...
    def __len__(self) -> int: ...
    def tolist(self) -> Any: ...
    # Returns a shared view when possible; otherwise returns a copy.
    @overload
    def reshape(self, shape: tuple[int, ...], /) -> Array: ...
    @overload
    def reshape(self, *shape: int) -> Array: ...
    def ravel(self) -> Array:
        """Return a one-dimensional view when storage is C-contiguous.

        Other layouts return a writable contiguous copy.
        """
    def copy(self) -> Array: ...
    def __copy__(self) -> Array: ...
    def __deepcopy__(self, memo: dict[int, Any]) -> Array: ...
    def astype(self, dtype: object) -> Array: ...
    def lens(self) -> ArrayLens: ...
    def sum(
        self,
        axis: int | None = None,
        dtype: None = None,
        out: None = None,
        keepdims: Literal[False] = False,
        initial: None = None,
        where: Literal[True] = True,
    ) -> bool | int | float | Array: ...
    def mean(
        self,
        axis: int | None = None,
        dtype: None = None,
        out: None = None,
        keepdims: Literal[False] = False,
        where: Literal[True] = True,
    ) -> float | Array: ...
    def min(
        self,
        axis: int | None = None,
        out: None = None,
        keepdims: Literal[False] = False,
        initial: None = None,
        where: Literal[True] = True,
    ) -> bool | int | float | Array: ...
    def max(
        self,
        axis: int | None = None,
        out: None = None,
        keepdims: Literal[False] = False,
        initial: None = None,
        where: Literal[True] = True,
    ) -> bool | int | float | Array: ...
    def all(
        self,
        axis: int | None = None,
        out: None = None,
        keepdims: Literal[False] = False,
        *,
        where: Literal[True] = True,
    ) -> bool | Array: ...
    def any(
        self,
        axis: int | None = None,
        out: None = None,
        keepdims: Literal[False] = False,
        *,
        where: Literal[True] = True,
    ) -> bool | Array: ...
    def to_numpy(self) -> Any: ...
    # Basic slices share storage; boolean-mask indexing returns a copy.
    @overload
    def __getitem__(self, index: slice, /) -> Array: ...
    @overload
    def __getitem__(self, index: Array, /) -> Array: ...
    @overload
    def __getitem__(
        self, index: int | tuple[int | slice, ...], /
    ) -> bool | int | float | Array: ...
    def __setitem__(self, index: object, value: object) -> None: ...
    def __eq__(self, other: object) -> Array: ...  # type: ignore[override]
    def __ne__(self, other: object) -> Array: ...  # type: ignore[override]
    def __lt__(self, other: object) -> Array: ...
    def __le__(self, other: object) -> Array: ...
    def __gt__(self, other: object) -> Array: ...
    def __ge__(self, other: object) -> Array: ...
    def __add__(self, other: object) -> Array: ...
    def __radd__(self, other: object) -> Array: ...
    def __iadd__(self, other: object) -> Array: ...
    def __sub__(self, other: object) -> Array: ...
    def __rsub__(self, other: object) -> Array: ...
    def __isub__(self, other: object) -> Array: ...
    def __mul__(self, other: object) -> Array: ...
    def __rmul__(self, other: object) -> Array: ...
    def __imul__(self, other: object) -> Array: ...
    def __truediv__(self, other: object) -> Array: ...
    def __rtruediv__(self, other: object) -> Array: ...
    def __itruediv__(self, other: object) -> Array: ...
    def __pow__(self, other: object, modulo: None = None) -> Array: ...
    def __rpow__(self, other: object, modulo: None = None) -> Array: ...
    def __ipow__(self, other: object, modulo: None = None) -> Array: ...
    def __mod__(self, other: object) -> Array: ...
    def __rmod__(self, other: object) -> Array: ...
    def __imod__(self, other: object) -> Array: ...
    def __neg__(self) -> Array: ...
    def __abs__(self) -> Array: ...
    def __bool__(self) -> bool: ...

class ArrayLens:
    def __getitem__(self, lane: int) -> FieldExpr: ...
    def __setitem__(self, lane: int, expression: Expr | float | int) -> None: ...

def array(obj: object, dtype: dtype | str | None = None) -> Array: ...
def asarray(obj: object, dtype: dtype | str | None = None) -> Array: ...
def from_dlpack(obj: object) -> Array: ...
def zeros(shape: int | tuple[int, ...], dtype: dtype | str | None = None) -> Array: ...
def ones(shape: int | tuple[int, ...], dtype: dtype | str | None = None) -> Array: ...
def full(
    shape: int | tuple[int, ...],
    fill_value: bool | int | float,
    dtype: dtype | str | None = None,
) -> Array: ...
def empty(shape: int | tuple[int, ...], dtype: dtype | str | None = None) -> Array: ...
def arange(
    start: bool | int | float,
    stop: bool | int | float | None = None,
    step: bool | int | float | None = None,
    dtype: dtype | str | None = None,
) -> Array: ...
def linspace(
    start: float,
    stop: float,
    num: int = 50,
    dtype: dtype | str | None = None,
) -> Array: ...

def sin(a: object) -> Array: ...
def cos(a: object) -> Array: ...
def tan(a: object) -> Array: ...
def sqrt(a: object) -> Array: ...
def exp(a: object) -> Array: ...
def log(a: object) -> Array: ...
def log10(a: object) -> Array: ...
def log2(a: object) -> Array: ...
def floor(a: object) -> Array: ...
def ceil(a: object) -> Array: ...
def round(a: object) -> Array: ...
def sign(a: object) -> Array: ...
def minimum(a: object, b: object) -> Array: ...
def maximum(a: object, b: object) -> Array: ...
def clip(a: object, min: object, max: object) -> Array: ...
def where(condition: object, x: object, y: object) -> Array: ...
def abs(a: object) -> Array: ...

def sum(a: object, axis: int | None = None) -> bool | int | float | Array: ...
def min(a: object, axis: int | None = None) -> bool | int | float | Array: ...
def max(a: object, axis: int | None = None) -> bool | int | float | Array: ...
def mean(a: object, axis: int | None = None) -> float | Array: ...
def all(a: object, axis: int | None = None) -> bool | Array: ...
def any(a: object, axis: int | None = None) -> bool | Array: ...

def isfinite(a: object) -> Array: ...
def isclose(a: object, b: object) -> Array: ...
def allclose(a: object, b: object) -> bool: ...
def array_equal(a: object, b: object) -> bool: ...

__pybevy_implementation__: str
