from collections.abc import Iterable, Iterator
from typing import Protocol, runtime_checkable

@runtime_checkable
class LiveSequence[T_co](Protocol):
    """Read-only indexed access into live engine-owned storage."""

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> T_co: ...
    def __iter__(self) -> Iterator[T_co]: ...
    def to_list(self) -> list[T_co]: ...

@runtime_checkable
class LiveList[T](LiveSequence[T], Protocol):
    """Mutable indexed access into live engine-owned storage."""

    def __setitem__(self, index: int, value: T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def append(self, value: T) -> None: ...
    def extend(self, values: Iterable[T]) -> None: ...
    def insert(self, index: int, value: T) -> None: ...
    def pop(self, index: int = -1) -> T: ...
    def clear(self) -> None: ...
