from collections.abc import Iterable, Iterator
from typing import Protocol, TypeVar, runtime_checkable

_T_co = TypeVar("_T_co", covariant=True)
_T = TypeVar("_T")


@runtime_checkable
class LiveSequence(Protocol[_T_co]):
    """Read-only indexed access into live engine-owned storage."""

    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> _T_co: ...
    def __iter__(self) -> Iterator[_T_co]: ...
    def to_list(self) -> list[_T_co]:
        """Return detached owned snapshots of the current elements."""


@runtime_checkable
class LiveList(LiveSequence[_T], Protocol[_T]):
    """Mutable indexed access into live engine-owned storage."""

    def __setitem__(self, index: int, value: _T) -> None: ...
    def __delitem__(self, index: int) -> None: ...
    def append(self, value: _T) -> None: ...
    def extend(self, values: Iterable[_T]) -> None: ...
    def insert(self, index: int, value: _T) -> None: ...
    def pop(self, index: int = -1) -> _T: ...
    def clear(self) -> None: ...
