from typing import ClassVar, Literal

from pybevy.app import App, Plugin
from pybevy.assets import Asset, AssetPath, Handle
from pybevy.ecs import Component
from pybevy.image import ImageSamplerDescriptor, RenderAssetUsages
from pybevy.transform import Transform

class GltfPlugin(Plugin):
    def __init__(self) -> None: ...
    def build(self, app: App) -> None: ...

class Gltf(Asset):
    """Representation of a loaded glTF file."""

    @property
    def scenes(self) -> list[Handle]: ...
    @property
    def named_scenes(self) -> list[tuple[str, Handle]]: ...
    @property
    def meshes(self) -> list[Handle]: ...
    @property
    def named_meshes(self) -> list[tuple[str, Handle]]: ...
    @property
    def materials(self) -> list[Handle]: ...
    @property
    def named_materials(self) -> list[tuple[str, Handle]]: ...
    @property
    def nodes(self) -> list[Handle]: ...
    @property
    def named_nodes(self) -> list[tuple[str, Handle]]: ...
    @property
    def skins(self) -> list[Handle]: ...
    @property
    def named_skins(self) -> list[tuple[str, Handle]]: ...
    @property
    def default_scene(self) -> Handle | None: ...

class GltfMesh(Asset):
    """A glTF mesh, which may consist of multiple primitives."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def primitives(self) -> list[GltfPrimitive]: ...
    @property
    def extras(self) -> str | None:
        """Additional untyped data from the glTF file (JSON string)."""
    def asset_label(self) -> GltfAssetLabel: ...

class GltfNode(Asset):
    """A glTF node with its children, mesh, transform, and skin."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def children(self) -> list[Handle]: ...
    @property
    def mesh(self) -> Handle | None: ...
    @property
    def skin(self) -> Handle | None: ...
    @property
    def transform(self) -> Transform: ...
    @property
    def extras(self) -> str | None:
        """Additional untyped data from the glTF file (JSON string)."""
    def asset_label(self) -> GltfAssetLabel: ...

class GltfPrimitive(Asset):
    """Part of a GltfMesh consisting of a mesh and optional material."""

    @property
    def index(self) -> int: ...
    @property
    def parent_mesh_index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def mesh(self) -> Handle: ...
    @property
    def material(self) -> Handle | None: ...
    @property
    def extras(self) -> str | None:
        """Additional untyped data from the glTF file (JSON string)."""
    @property
    def material_extras(self) -> str | None:
        """Additional untyped material data from the glTF file (JSON string)."""
    def asset_label(self) -> GltfAssetLabel: ...

class GltfSkin(Asset):
    """A glTF skin with joint nodes and inverse-bind matrices."""

    @property
    def index(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def joints(self) -> list[Handle]: ...
    @property
    def inverse_bind_matrices(self) -> Handle: ...
    @property
    def extras(self) -> str | None:
        """Additional untyped data from the glTF file (JSON string)."""
    def asset_label(self) -> GltfAssetLabel: ...

class GltfExtras(Component):
    """Additional untyped data that can be present on GLTF types at the primitive level."""

    def __init__(self, value: str = "") -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...

class GltfMeshName(Component):
    """The mesh name of a glTF primitive."""

    def __init__(self, name: str = "") -> None: ...
    @property
    def name(self) -> str: ...
    def __str__(self) -> str: ...

class GltfMaterialName(Component):
    """The material name of a glTF primitive."""

    def __init__(self, name: str = "") -> None: ...
    @property
    def name(self) -> str: ...
    def __str__(self) -> str: ...

class GltfSceneExtras(Component):
    """Additional untyped data that can be present on GLTF types at the scene level."""

    def __init__(self, value: str = "") -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...

class GltfMeshExtras(Component):
    """Additional untyped data that can be present on GLTF types at the mesh level."""

    def __init__(self, value: str = "") -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...

class GltfMaterialExtras(Component):
    """Additional untyped data that can be present on GLTF types at the material level."""

    def __init__(self, value: str = "") -> None: ...
    @property
    def value(self) -> str: ...
    @value.setter
    def value(self, value: str) -> None: ...

class GltfLoaderSettings:
    """Settings for loading glTF files."""

    def __init__(
        self,
        load_meshes: RenderAssetUsages | None = None,
        load_materials: RenderAssetUsages | None = None,
        load_cameras: bool = True,
        load_lights: bool = True,
        load_animations: bool = True,
        include_source: bool = False,
        default_sampler: ImageSamplerDescriptor | None = None,
        override_sampler: bool = False,
    ) -> None: ...
    @property
    def load_meshes(self) -> RenderAssetUsages: ...
    @load_meshes.setter
    def load_meshes(self, value: RenderAssetUsages) -> None: ...
    @property
    def load_materials(self) -> RenderAssetUsages: ...
    @load_materials.setter
    def load_materials(self, value: RenderAssetUsages) -> None: ...
    @property
    def load_cameras(self) -> bool: ...
    @load_cameras.setter
    def load_cameras(self, value: bool) -> None: ...
    @property
    def load_lights(self) -> bool: ...
    @load_lights.setter
    def load_lights(self, value: bool) -> None: ...
    @property
    def load_animations(self) -> bool: ...
    @load_animations.setter
    def load_animations(self, value: bool) -> None: ...
    @property
    def include_source(self) -> bool: ...
    @include_source.setter
    def include_source(self, value: bool) -> None: ...
    @property
    def default_sampler(self) -> ImageSamplerDescriptor | None: ...
    @default_sampler.setter
    def default_sampler(self, value: ImageSamplerDescriptor | None) -> None: ...
    @property
    def override_sampler(self) -> bool: ...
    @override_sampler.setter
    def override_sampler(self, value: bool) -> None: ...
class GltfAssetLabel:
    class Scene(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    class Node(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    class Mesh(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    class Primitive(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["mesh"], Literal["primitive"]]]
        mesh: int
        primitive: int
        def __init__(self, mesh: int, primitive: int) -> None: ...

    class Texture(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    class Material(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"], Literal["is_scale_inverted"]]]
        index: int
        is_scale_inverted: bool
        def __init__(self, index: int, is_scale_inverted: bool) -> None:
            """Label for the GltfMaterial sub-asset of a glTF file.

            The processed StandardMaterial lives under the "/std" suffix; load it
            with an explicit label, e.g.
            ``AssetPath(path, label=f"{GltfAssetLabel.Material(0, False)}/std")``.
            """

    class DefaultMaterial(GltfAssetLabel):
        __match_args__: ClassVar[tuple[()]]
        def __init__(self) -> None: ...

    class Animation(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    class Skin(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    class InverseBindMatrices(GltfAssetLabel):
        __match_args__: ClassVar[tuple[Literal["index"]]]
        index: int
        def __init__(self, index: int) -> None: ...

    def from_asset(self, path: str) -> AssetPath: ...
    def __str__(self) -> str: ...
