from typing import Optional

from .animation import (
    AnimatableCurve,
    AnimatableKeyframeCurve,
    AnimatedField,
    AnimationClip,
    AnimationGraph,
    AnimationGraphHandle,
    AnimationGraphNode,
    AnimationNodeIndex,
    AnimationPlayer,
    AnimationPlugin,
    AnimationTransitions,
    VariableCurve,
    WeightsCurve,
)
from .app import (
    App,
    AppExit,
    DefaultPlugins,
    MinimalPlugins,
    Plugin,
    PluginGroup,
    Stage,
    TaskPoolPlugin,
    chain,
)
from .assets import Asset, AssetEvent, AssetId, AssetPlugin, Assets, AssetServer, Handle
from .audio import (
    AudioPlayer,
    AudioSink,
    AudioSource,
    GlobalVolume,
    Pitch,
    PlaybackSettings,
    SpatialAudioSink,
    SpatialListener,
    Volume,
)
from .camera import (
    Camera,
    Camera2d,
    Camera3d,
    ClearColor,
    ClearColorConfig,
    InheritedVisibility,
    OrthographicProjection,
    PerspectiveProjection,
    Projection,
    ScalingMode,
    ViewVisibility,
    Visibility,
)
from .color import (
    Color,
    Hsla,
    Hsva,
    Hwba,
    Laba,
    Lcha,
    LinearRgba,
    Oklaba,
    Oklcha,
    Srgba,
    Xyza,
)
from .core_pipeline import Tonemapping
from .decorators import (
    component,
    entrypoint,
    event,
    material,
    message,
    plugin,
    resource,
)
from .ecs import (
    Add,
    Added,
    AnyOf,
    Changed,
    ChildOf,
    Children,
    Commands,
    Component,
    Despawn,
    DespawnOnExit,
    Discard,
    Entity,
    EntityCommands,
    Event,
    Has,
    In,
    Insert,
    Local,
    Message,
    MessageMutator,
    MessageReader,
    Messages,
    MessageWriter,
    Mut,
    Name,
    NextState,
    On,
    OnEnter,
    OnExit,
    OnTransition,
    Or,
    Query,
    Remove,
    Res,
    ResMut,
    Resource,
    Single,
    State,
    SystemSet,
    SystemSetEnum,
    View,
    With,
    Without,
    World,
    in_state,
    pipe,
    run_if,
    state,
    system,
    system_set,
)
from .expr import FieldExpr
from .gizmos import (
    GizmoConfig,
    GizmoConfigGroup,
    GizmoConfigStore,
    GizmoLineConfig,
    GizmoLineJoint,
    GizmoLineStyle,
    Gizmos,
    ShowAabbGizmo,
)
from .gltf import Gltf, GltfAssetLabel, GltfExtras
from .image import (
    Image,
    ImagePlugin,
    TextureAtlas,
    TextureAtlasLayout,
    TextureAtlasSources,
)
from .input import (
    ButtonInput,
    Gamepad,
    GamepadAxis,
    GamepadButton,
    GamepadSettings,
    KeyCode,
    MouseButton,
    Touches,
    TouchInput,
)
from .light import (
    AmbientLight,
    DirectionalLight,
    EnvironmentMapLight,
    GeneratedEnvironmentMapLight,
    GlobalAmbientLight,
    LightGizmoColor,
    LightGizmoConfigGroup,
    LightProbe,
    PointLight,
    RectLight,
    ShowLightGizmo,
    SpotLight,
)
from .material import AlphaMode
from .math import (
    Annulus,
    Capsule2d,
    Capsule3d,
    Circle,
    CircularSector,
    CircularSegment,
    Cone,
    Cuboid,
    Cylinder,
    Dir2,
    Dir3,
    EaseFunction,
    Ellipse,
    EulerRot,
    InfinitePlane3d,
    Interval,
    IRect,
    Isometry2d,
    Isometry3d,
    IVec2,
    JumpAt,
    Mat2,
    Mat3,
    Mat3A,
    Mat4,
    Plane3d,
    Quat,
    Ray2d,
    Ray3d,
    Rect,
    Rectangle,
    RegularPolygon,
    Rhombus,
    Segment2d,
    Sphere,
    Tetrahedron,
    Torus,
    Triangle2d,
    Triangle3d,
    URect,
    UVec2,
    UVec3,
    Vec2,
    Vec3,
    Vec3A,
    Vec4,
)
from .mesh import (
    Mesh,
    Mesh2d,
    Mesh3d,
    MeshMaterial2d,
    MeshMaterial3d,
    MorphWeights,
    PrimitiveTopology,
)
from .pbr import (
    DistanceFog,
    FogFalloff,
    Material,
    ParallaxMappingMethod,
    StandardMaterial,
)
from .post_process import Bloom, BloomCompositeMode, BloomPrefilter
from .render import Msaa
from .shader import Shader
from .sprite import (
    ColorMaterial,
    SliceScaleMode,
    Sprite,
    SpriteImageMode,
    TextureSlicer,
)
from .text import (
    Font,
    Justify,
    LineBreak,
    Text2d,
    TextBackgroundColor,
    TextColor,
    TextFont,
    TextLayout,
    TextSpan,
)
from .time import Fixed, Real, Time, Timer, TimerMode, Virtual
from .transform import GlobalTransform, Transform, TransformPlugin
from .ui import (
    AlignContent,
    AlignItems,
    AlignSelf,
    BackgroundColor,
    BorderColor,
    BorderGradient,
    BorderRadius,
    BoxSizing,
    Button,
    Display,
    FlexDirection,
    FlexWrap,
    GlobalZIndex,
    GridAutoFlow,
    GridPlacement,
    GridTrack,
    ImageNode,
    InlineDirection,
    Interaction,
    IsDefaultUiCamera,
    JustifyContent,
    JustifyItems,
    JustifySelf,
    Label,
    Node,
    NodeImageMode,
    Outline,
    Overflow,
    OverflowAxis,
    OverflowClipMargin,
    PositionType,
    RepeatedGridTrack,
    Text,
    UiRect,
    UiTargetCamera,
    Val,
    Val2,
    VisualBox,
    ZIndex,
)
from .window import (
    CursorEntered,
    CursorLeft,
    CursorMoved,
    FileDragAndDrop,
    Ime,
    MonitorSelection,
    VideoModeSelection,
    Window,
    WindowPlugin,
    WindowPosition,
    WindowResizeConstraints,
)
from .world_serialization import (
    DynamicWorld,
    DynamicWorldRoot,
    WorldAsset,
    WorldAssetRoot,
    WorldInstanceSpawner,
)

# Schedule aliases
Startup = Stage.Startup
Update = Stage.Update
Last = Stage.Last
FixedUpdate = Stage.FixedUpdate
SimTick = Stage.SimTick
First = Stage.First
PreStartup = Stage.PreStartup
PostStartup = Stage.PostStartup
PreUpdate = Stage.PreUpdate
PostUpdate = Stage.PostUpdate
Main = Stage.Main
FixedFirst = Stage.FixedFirst
FixedPreUpdate = Stage.FixedPreUpdate
FixedPostUpdate = Stage.FixedPostUpdate
FixedLast = Stage.FixedLast


__all__ = [
    # Animation
    "AnimatableCurve",
    "AnimatableKeyframeCurve",
    "AnimatedField",
    "AnimationClip",
    "AnimationGraph",
    "AnimationGraphHandle",
    "AnimationGraphNode",
    "AnimationNodeIndex",
    "AnimationPlayer",
    "AnimationPlugin",
    "AnimationTransitions",
    "VariableCurve",
    "WeightsCurve",
    # App
    "App",
    "AppExit",
    "DefaultPlugins",
    "MinimalPlugins",
    "Plugin",
    "PluginGroup",
    "Stage",
    "TaskPoolPlugin",
    "chain",
    # Assets
    "Asset",
    "AssetEvent",
    "AssetId",
    "AssetPlugin",
    "AssetServer",
    "Assets",
    "Handle",
    # Audio
    "AudioPlayer",
    "AudioSink",
    "AudioSource",
    "GlobalVolume",
    "Pitch",
    "PlaybackSettings",
    "SpatialAudioSink",
    "SpatialListener",
    "Volume",
    # Camera
    "Bloom",
    "BloomCompositeMode",
    "BloomPrefilter",
    "Camera",
    "Camera2d",
    "Camera3d",
    "ClearColor",
    "ClearColorConfig",
    "InheritedVisibility",
    "Msaa",
    "OrthographicProjection",
    "PerspectiveProjection",
    "Projection",
    "ScalingMode",
    "Tonemapping",
    "ViewVisibility",
    "Visibility",
    # Color
    "Color",
    "Hsla",
    "Hsva",
    "Hwba",
    "Laba",
    "Lcha",
    "LinearRgba",
    "Oklaba",
    "Oklcha",
    "Srgba",
    "Xyza",
    # Decorators (PyBevy-specific)
    "component",
    "entrypoint",
    "event",
    "Material",
    "material",
    "message",
    "plugin",
    "resource",
    # ECS
    "Added",
    "AnyOf",
    "Changed",
    "ChildOf",
    "Children",
    "Commands",
    "Component",
    "DespawnOnExit",
    "Entity",
    "EntityCommands",
    "Event",
    "Has",
    "In",
    "in_state",
    "Local",
    "Message",
    "MessageMutator",
    "MessageReader",
    "MessageWriter",
    "Messages",
    "Mut",
    "Name",
    "NextState",
    "Add",
    "Despawn",
    "Discard",
    "Insert",
    "On",
    "OnEnter",
    "OnExit",
    "OnTransition",
    "Or",
    "Remove",
    "Query",
    "Res",
    "ResMut",
    "Resource",
    "Single",
    "State",
    "state",
    "View",
    "With",
    "Without",
    "World",
    "pipe",
    "run_if",
    "system",
    "system_set",
    "SystemSet",
    "SystemSetEnum",
    # Expr (PyBevy-specific)
    "FieldExpr",
    # Gizmos
    "GizmoConfig",
    "GizmoConfigGroup",
    "GizmoConfigStore",
    "GizmoLineConfig",
    "GizmoLineJoint",
    "GizmoLineStyle",
    "Gizmos",
    "ShowAabbGizmo",
    # GLTF
    "Gltf",
    "GltfAssetLabel",
    "GltfExtras",
    # Image
    "Image",
    "ImagePlugin",
    "TextureAtlas",
    "TextureAtlasLayout",
    "TextureAtlasSources",
    # Input
    "ButtonInput",
    "Gamepad",
    "GamepadAxis",
    "GamepadButton",
    "GamepadSettings",
    "KeyCode",
    "MouseButton",
    "TouchInput",
    "Touches",
    # Light
    "AmbientLight",
    "DirectionalLight",
    "EnvironmentMapLight",
    "GeneratedEnvironmentMapLight",
    "GlobalAmbientLight",
    "LightProbe",
    "LightGizmoColor",
    "LightGizmoConfigGroup",
    "PointLight",
    "RectLight",
    "ShowLightGizmo",
    "SpotLight",
    # Math
    "Annulus",
    "Capsule2d",
    "Capsule3d",
    "Circle",
    "CircularSector",
    "CircularSegment",
    "Cone",
    "Cuboid",
    "Cylinder",
    "Dir2",
    "Dir3",
    "EaseFunction",
    "Ellipse",
    "EulerRot",
    "InfinitePlane3d",
    "Isometry2d",
    "Isometry3d",
    "IVec2",
    "IRect",
    "Interval",
    "JumpAt",
    "Mat2",
    "Mat3",
    "Mat3A",
    "Mat4",
    "Plane3d",
    "Quat",
    "Ray2d",
    "Ray3d",
    "Rect",
    "Rectangle",
    "RegularPolygon",
    "Rhombus",
    "Segment2d",
    "Sphere",
    "Tetrahedron",
    "Torus",
    "Triangle2d",
    "Triangle3d",
    "URect",
    "UVec2",
    "UVec3",
    "Vec2",
    "Vec3",
    "Vec3A",
    "Vec4",
    # Mesh
    "Mesh",
    "Mesh2d",
    "Mesh3d",
    "MeshMaterial2d",
    "MeshMaterial3d",
    "MorphWeights",
    "PrimitiveTopology",
    # PBR
    "AlphaMode",
    "DistanceFog",
    "FogFalloff",
    "ParallaxMappingMethod",
    "StandardMaterial",
    # World serialization
    "DynamicWorld",
    "DynamicWorldRoot",
    "WorldAsset",
    "WorldAssetRoot",
    "WorldInstanceSpawner",
    # Shader
    "Shader",
    # Sprite
    "ColorMaterial",
    "SliceScaleMode",
    "Sprite",
    "SpriteImageMode",
    "TextureSlicer",
    # Text
    "Font",
    "Justify",
    "LineBreak",
    "Text2d",
    "TextBackgroundColor",
    "TextColor",
    "TextFont",
    "TextLayout",
    "TextSpan",
    # Time
    "Fixed",
    "Real",
    "Time",
    "Timer",
    "TimerMode",
    "Virtual",
    # Transform
    "GlobalTransform",
    "Transform",
    "TransformPlugin",
    # UI
    "AlignContent",
    "AlignItems",
    "AlignSelf",
    "BackgroundColor",
    "BorderColor",
    "BorderGradient",
    "BorderRadius",
    "BoxSizing",
    "Button",
    "Display",
    "FlexDirection",
    "FlexWrap",
    "GlobalZIndex",
    "InlineDirection",
    "GridAutoFlow",
    "GridPlacement",
    "GridTrack",
    "ImageNode",
    "Interaction",
    "IsDefaultUiCamera",
    "JustifyContent",
    "JustifyItems",
    "JustifySelf",
    "Label",
    "Node",
    "NodeImageMode",
    "Outline",
    "Overflow",
    "OverflowAxis",
    "VisualBox",
    "OverflowClipMargin",
    "PositionType",
    "RepeatedGridTrack",
    "Text",
    "UiRect",
    "UiTargetCamera",
    "Val",
    "Val2",
    "ZIndex",
    # Window
    "CursorEntered",
    "CursorLeft",
    "CursorMoved",
    "FileDragAndDrop",
    "Ime",
    "MonitorSelection",
    "VideoModeSelection",
    "Window",
    "WindowPlugin",
    "WindowPosition",
    "WindowResizeConstraints",
    # Typing re-exports
    "Optional",
    # Schedule aliases
    "First",
    "FixedFirst",
    "FixedLast",
    "FixedPostUpdate",
    "FixedPreUpdate",
    "FixedUpdate",
    "Last",
    "Main",
    "PostStartup",
    "PostUpdate",
    "PreStartup",
    "PreUpdate",
    "SimTick",
    "Startup",
    "Update",
]
