use accesskit::Role;
use pyo3::prelude::*;

#[pyclass(
    name = "Role",
    module = "pybevy.a11y",
    eq,
    frozen,
    from_py_object,
    hash
)]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PyRole {
    Unknown,
    TextRun,
    Cell,
    Label,
    Image,
    Link,
    Row,
    ListItem,
    ListMarker,
    TreeItem,
    ListBoxOption,
    MenuItem,
    MenuListOption,
    Paragraph,
    GenericContainer,
    CheckBox,
    RadioButton,
    TextInput,
    Button,
    DefaultButton,
    Pane,
    RowHeader,
    ColumnHeader,
    RowGroup,
    List,
    Table,
    LayoutTableCell,
    LayoutTableRow,
    LayoutTable,
    Switch,
    Menu,
    MultilineTextInput,
    SearchInput,
    DateInput,
    DateTimeInput,
    WeekInput,
    MonthInput,
    TimeInput,
    EmailInput,
    NumberInput,
    PasswordInput,
    PhoneNumberInput,
    UrlInput,
    Abbr,
    Alert,
    AlertDialog,
    Application,
    Article,
    Audio,
    Banner,
    Blockquote,
    Canvas,
    Caption,
    Caret,
    Code,
    ColorWell,
    ComboBox,
    EditableComboBox,
    Complementary,
    Comment,
    ContentDeletion,
    ContentInsertion,
    ContentInfo,
    Definition,
    DescriptionList,
    Details,
    Dialog,
    DisclosureTriangle,
    Document,
    EmbeddedObject,
    Emphasis,
    Feed,
    FigureCaption,
    Figure,
    Footer,
    Form,
    Grid,
    GridCell,
    Group,
    Header,
    Heading,
    Iframe,
    IframePresentational,
    ImeCandidate,
    Keyboard,
    Legend,
    LineBreak,
    ListBox,
    Log,
    Main,
    Mark,
    Marquee,
    Math,
    MenuBar,
    MenuItemCheckBox,
    MenuItemRadio,
    MenuListPopup,
    Meter,
    Navigation,
    Note,
    PluginObject,
    ProgressIndicator,
    RadioGroup,
    Region,
    RootWebArea,
    Ruby,
    RubyAnnotation,
    ScrollBar,
    ScrollView,
    Search,
    Section,
    SectionFooter,
    SectionHeader,
    Slider,
    SpinButton,
    Splitter,
    Status,
    Strong,
    Suggestion,
    SvgRoot,
    Tab,
    TabList,
    TabPanel,
    Term,
    Time,
    Timer,
    TitleBar,
    Toolbar,
    Tooltip,
    Tree,
    TreeGrid,
    Video,
    WebView,
    Window,
    PdfActionableHighlight,
    PdfRoot,
    GraphicsDocument,
    GraphicsObject,
    GraphicsSymbol,
    DocAbstract,
    DocAcknowledgements,
    DocAfterword,
    DocAppendix,
    DocBackLink,
    DocBiblioEntry,
    DocBibliography,
    DocBiblioRef,
    DocChapter,
    DocColophon,
    DocConclusion,
    DocCover,
    DocCredit,
    DocCredits,
    DocDedication,
    DocEndnote,
    DocEndnotes,
    DocEpigraph,
    DocEpilogue,
    DocErrata,
    DocExample,
    DocFootnote,
    DocForeword,
    DocGlossary,
    DocGlossRef,
    DocIndex,
    DocIntroduction,
    DocNoteRef,
    DocNotice,
    DocPageBreak,
    DocPageFooter,
    DocPageHeader,
    DocPageList,
    DocPart,
    DocPreface,
    DocPrologue,
    DocPullquote,
    DocQna,
    DocSubtitle,
    DocTip,
    DocToc,
    ListGrid,
    Terminal,
}

impl From<PyRole> for Role {
    fn from(role: PyRole) -> Self {
        match role {
            PyRole::Unknown => Role::Unknown,
            PyRole::TextRun => Role::TextRun,
            PyRole::Cell => Role::Cell,
            PyRole::Label => Role::Label,
            PyRole::Image => Role::Image,
            PyRole::Link => Role::Link,
            PyRole::Row => Role::Row,
            PyRole::ListItem => Role::ListItem,
            PyRole::ListMarker => Role::ListMarker,
            PyRole::TreeItem => Role::TreeItem,
            PyRole::ListBoxOption => Role::ListBoxOption,
            PyRole::MenuItem => Role::MenuItem,
            PyRole::MenuListOption => Role::MenuListOption,
            PyRole::Paragraph => Role::Paragraph,
            PyRole::GenericContainer => Role::GenericContainer,
            PyRole::CheckBox => Role::CheckBox,
            PyRole::RadioButton => Role::RadioButton,
            PyRole::TextInput => Role::TextInput,
            PyRole::Button => Role::Button,
            PyRole::DefaultButton => Role::DefaultButton,
            PyRole::Pane => Role::Pane,
            PyRole::RowHeader => Role::RowHeader,
            PyRole::ColumnHeader => Role::ColumnHeader,
            PyRole::RowGroup => Role::RowGroup,
            PyRole::List => Role::List,
            PyRole::Table => Role::Table,
            PyRole::LayoutTableCell => Role::LayoutTableCell,
            PyRole::LayoutTableRow => Role::LayoutTableRow,
            PyRole::LayoutTable => Role::LayoutTable,
            PyRole::Switch => Role::Switch,
            PyRole::Menu => Role::Menu,
            PyRole::MultilineTextInput => Role::MultilineTextInput,
            PyRole::SearchInput => Role::SearchInput,
            PyRole::DateInput => Role::DateInput,
            PyRole::DateTimeInput => Role::DateTimeInput,
            PyRole::WeekInput => Role::WeekInput,
            PyRole::MonthInput => Role::MonthInput,
            PyRole::TimeInput => Role::TimeInput,
            PyRole::EmailInput => Role::EmailInput,
            PyRole::NumberInput => Role::NumberInput,
            PyRole::PasswordInput => Role::PasswordInput,
            PyRole::PhoneNumberInput => Role::PhoneNumberInput,
            PyRole::UrlInput => Role::UrlInput,
            PyRole::Abbr => Role::Abbr,
            PyRole::Alert => Role::Alert,
            PyRole::AlertDialog => Role::AlertDialog,
            PyRole::Application => Role::Application,
            PyRole::Article => Role::Article,
            PyRole::Audio => Role::Audio,
            PyRole::Banner => Role::Banner,
            PyRole::Blockquote => Role::Blockquote,
            PyRole::Canvas => Role::Canvas,
            PyRole::Caption => Role::Caption,
            PyRole::Caret => Role::Caret,
            PyRole::Code => Role::Code,
            PyRole::ColorWell => Role::ColorWell,
            PyRole::ComboBox => Role::ComboBox,
            PyRole::EditableComboBox => Role::EditableComboBox,
            PyRole::Complementary => Role::Complementary,
            PyRole::Comment => Role::Comment,
            PyRole::ContentDeletion => Role::ContentDeletion,
            PyRole::ContentInsertion => Role::ContentInsertion,
            PyRole::ContentInfo => Role::ContentInfo,
            PyRole::Definition => Role::Definition,
            PyRole::DescriptionList => Role::DescriptionList,
            PyRole::Details => Role::Details,
            PyRole::Dialog => Role::Dialog,
            PyRole::DisclosureTriangle => Role::DisclosureTriangle,
            PyRole::Document => Role::Document,
            PyRole::EmbeddedObject => Role::EmbeddedObject,
            PyRole::Emphasis => Role::Emphasis,
            PyRole::Feed => Role::Feed,
            PyRole::FigureCaption => Role::FigureCaption,
            PyRole::Figure => Role::Figure,
            PyRole::Footer => Role::Footer,
            PyRole::Form => Role::Form,
            PyRole::Grid => Role::Grid,
            PyRole::GridCell => Role::GridCell,
            PyRole::Group => Role::Group,
            PyRole::Header => Role::Header,
            PyRole::Heading => Role::Heading,
            PyRole::Iframe => Role::Iframe,
            PyRole::IframePresentational => Role::IframePresentational,
            PyRole::ImeCandidate => Role::ImeCandidate,
            PyRole::Keyboard => Role::Keyboard,
            PyRole::Legend => Role::Legend,
            PyRole::LineBreak => Role::LineBreak,
            PyRole::ListBox => Role::ListBox,
            PyRole::Log => Role::Log,
            PyRole::Main => Role::Main,
            PyRole::Mark => Role::Mark,
            PyRole::Marquee => Role::Marquee,
            PyRole::Math => Role::Math,
            PyRole::MenuBar => Role::MenuBar,
            PyRole::MenuItemCheckBox => Role::MenuItemCheckBox,
            PyRole::MenuItemRadio => Role::MenuItemRadio,
            PyRole::MenuListPopup => Role::MenuListPopup,
            PyRole::Meter => Role::Meter,
            PyRole::Navigation => Role::Navigation,
            PyRole::Note => Role::Note,
            PyRole::PluginObject => Role::PluginObject,
            PyRole::ProgressIndicator => Role::ProgressIndicator,
            PyRole::RadioGroup => Role::RadioGroup,
            PyRole::Region => Role::Region,
            PyRole::RootWebArea => Role::RootWebArea,
            PyRole::Ruby => Role::Ruby,
            PyRole::RubyAnnotation => Role::RubyAnnotation,
            PyRole::ScrollBar => Role::ScrollBar,
            PyRole::ScrollView => Role::ScrollView,
            PyRole::Search => Role::Search,
            PyRole::Section => Role::Section,
            PyRole::SectionFooter => Role::SectionFooter,
            PyRole::SectionHeader => Role::SectionHeader,
            PyRole::Slider => Role::Slider,
            PyRole::SpinButton => Role::SpinButton,
            PyRole::Splitter => Role::Splitter,
            PyRole::Status => Role::Status,
            PyRole::Strong => Role::Strong,
            PyRole::Suggestion => Role::Suggestion,
            PyRole::SvgRoot => Role::SvgRoot,
            PyRole::Tab => Role::Tab,
            PyRole::TabList => Role::TabList,
            PyRole::TabPanel => Role::TabPanel,
            PyRole::Term => Role::Term,
            PyRole::Time => Role::Time,
            PyRole::Timer => Role::Timer,
            PyRole::TitleBar => Role::TitleBar,
            PyRole::Toolbar => Role::Toolbar,
            PyRole::Tooltip => Role::Tooltip,
            PyRole::Tree => Role::Tree,
            PyRole::TreeGrid => Role::TreeGrid,
            PyRole::Video => Role::Video,
            PyRole::WebView => Role::WebView,
            PyRole::Window => Role::Window,
            PyRole::PdfActionableHighlight => Role::PdfActionableHighlight,
            PyRole::PdfRoot => Role::PdfRoot,
            PyRole::GraphicsDocument => Role::GraphicsDocument,
            PyRole::GraphicsObject => Role::GraphicsObject,
            PyRole::GraphicsSymbol => Role::GraphicsSymbol,
            PyRole::DocAbstract => Role::DocAbstract,
            PyRole::DocAcknowledgements => Role::DocAcknowledgements,
            PyRole::DocAfterword => Role::DocAfterword,
            PyRole::DocAppendix => Role::DocAppendix,
            PyRole::DocBackLink => Role::DocBackLink,
            PyRole::DocBiblioEntry => Role::DocBiblioEntry,
            PyRole::DocBibliography => Role::DocBibliography,
            PyRole::DocBiblioRef => Role::DocBiblioRef,
            PyRole::DocChapter => Role::DocChapter,
            PyRole::DocColophon => Role::DocColophon,
            PyRole::DocConclusion => Role::DocConclusion,
            PyRole::DocCover => Role::DocCover,
            PyRole::DocCredit => Role::DocCredit,
            PyRole::DocCredits => Role::DocCredits,
            PyRole::DocDedication => Role::DocDedication,
            PyRole::DocEndnote => Role::DocEndnote,
            PyRole::DocEndnotes => Role::DocEndnotes,
            PyRole::DocEpigraph => Role::DocEpigraph,
            PyRole::DocEpilogue => Role::DocEpilogue,
            PyRole::DocErrata => Role::DocErrata,
            PyRole::DocExample => Role::DocExample,
            PyRole::DocFootnote => Role::DocFootnote,
            PyRole::DocForeword => Role::DocForeword,
            PyRole::DocGlossary => Role::DocGlossary,
            PyRole::DocGlossRef => Role::DocGlossRef,
            PyRole::DocIndex => Role::DocIndex,
            PyRole::DocIntroduction => Role::DocIntroduction,
            PyRole::DocNoteRef => Role::DocNoteRef,
            PyRole::DocNotice => Role::DocNotice,
            PyRole::DocPageBreak => Role::DocPageBreak,
            PyRole::DocPageFooter => Role::DocPageFooter,
            PyRole::DocPageHeader => Role::DocPageHeader,
            PyRole::DocPageList => Role::DocPageList,
            PyRole::DocPart => Role::DocPart,
            PyRole::DocPreface => Role::DocPreface,
            PyRole::DocPrologue => Role::DocPrologue,
            PyRole::DocPullquote => Role::DocPullquote,
            PyRole::DocQna => Role::DocQna,
            PyRole::DocSubtitle => Role::DocSubtitle,
            PyRole::DocTip => Role::DocTip,
            PyRole::DocToc => Role::DocToc,
            PyRole::ListGrid => Role::ListGrid,
            PyRole::Terminal => Role::Terminal,
        }
    }
}

impl From<Role> for PyRole {
    fn from(role: Role) -> Self {
        match role {
            Role::Unknown => PyRole::Unknown,
            Role::TextRun => PyRole::TextRun,
            Role::Cell => PyRole::Cell,
            Role::Label => PyRole::Label,
            Role::Image => PyRole::Image,
            Role::Link => PyRole::Link,
            Role::Row => PyRole::Row,
            Role::ListItem => PyRole::ListItem,
            Role::ListMarker => PyRole::ListMarker,
            Role::TreeItem => PyRole::TreeItem,
            Role::ListBoxOption => PyRole::ListBoxOption,
            Role::MenuItem => PyRole::MenuItem,
            Role::MenuListOption => PyRole::MenuListOption,
            Role::Paragraph => PyRole::Paragraph,
            Role::GenericContainer => PyRole::GenericContainer,
            Role::CheckBox => PyRole::CheckBox,
            Role::RadioButton => PyRole::RadioButton,
            Role::TextInput => PyRole::TextInput,
            Role::Button => PyRole::Button,
            Role::DefaultButton => PyRole::DefaultButton,
            Role::Pane => PyRole::Pane,
            Role::RowHeader => PyRole::RowHeader,
            Role::ColumnHeader => PyRole::ColumnHeader,
            Role::RowGroup => PyRole::RowGroup,
            Role::List => PyRole::List,
            Role::Table => PyRole::Table,
            Role::LayoutTableCell => PyRole::LayoutTableCell,
            Role::LayoutTableRow => PyRole::LayoutTableRow,
            Role::LayoutTable => PyRole::LayoutTable,
            Role::Switch => PyRole::Switch,
            Role::Menu => PyRole::Menu,
            Role::MultilineTextInput => PyRole::MultilineTextInput,
            Role::SearchInput => PyRole::SearchInput,
            Role::DateInput => PyRole::DateInput,
            Role::DateTimeInput => PyRole::DateTimeInput,
            Role::WeekInput => PyRole::WeekInput,
            Role::MonthInput => PyRole::MonthInput,
            Role::TimeInput => PyRole::TimeInput,
            Role::EmailInput => PyRole::EmailInput,
            Role::NumberInput => PyRole::NumberInput,
            Role::PasswordInput => PyRole::PasswordInput,
            Role::PhoneNumberInput => PyRole::PhoneNumberInput,
            Role::UrlInput => PyRole::UrlInput,
            Role::Abbr => PyRole::Abbr,
            Role::Alert => PyRole::Alert,
            Role::AlertDialog => PyRole::AlertDialog,
            Role::Application => PyRole::Application,
            Role::Article => PyRole::Article,
            Role::Audio => PyRole::Audio,
            Role::Banner => PyRole::Banner,
            Role::Blockquote => PyRole::Blockquote,
            Role::Canvas => PyRole::Canvas,
            Role::Caption => PyRole::Caption,
            Role::Caret => PyRole::Caret,
            Role::Code => PyRole::Code,
            Role::ColorWell => PyRole::ColorWell,
            Role::ComboBox => PyRole::ComboBox,
            Role::EditableComboBox => PyRole::EditableComboBox,
            Role::Complementary => PyRole::Complementary,
            Role::Comment => PyRole::Comment,
            Role::ContentDeletion => PyRole::ContentDeletion,
            Role::ContentInsertion => PyRole::ContentInsertion,
            Role::ContentInfo => PyRole::ContentInfo,
            Role::Definition => PyRole::Definition,
            Role::DescriptionList => PyRole::DescriptionList,
            Role::Details => PyRole::Details,
            Role::Dialog => PyRole::Dialog,
            Role::DisclosureTriangle => PyRole::DisclosureTriangle,
            Role::Document => PyRole::Document,
            Role::EmbeddedObject => PyRole::EmbeddedObject,
            Role::Emphasis => PyRole::Emphasis,
            Role::Feed => PyRole::Feed,
            Role::FigureCaption => PyRole::FigureCaption,
            Role::Figure => PyRole::Figure,
            Role::Footer => PyRole::Footer,
            Role::Form => PyRole::Form,
            Role::Grid => PyRole::Grid,
            Role::GridCell => PyRole::GridCell,
            Role::Group => PyRole::Group,
            Role::Header => PyRole::Header,
            Role::Heading => PyRole::Heading,
            Role::Iframe => PyRole::Iframe,
            Role::IframePresentational => PyRole::IframePresentational,
            Role::ImeCandidate => PyRole::ImeCandidate,
            Role::Keyboard => PyRole::Keyboard,
            Role::Legend => PyRole::Legend,
            Role::LineBreak => PyRole::LineBreak,
            Role::ListBox => PyRole::ListBox,
            Role::Log => PyRole::Log,
            Role::Main => PyRole::Main,
            Role::Mark => PyRole::Mark,
            Role::Marquee => PyRole::Marquee,
            Role::Math => PyRole::Math,
            Role::MenuBar => PyRole::MenuBar,
            Role::MenuItemCheckBox => PyRole::MenuItemCheckBox,
            Role::MenuItemRadio => PyRole::MenuItemRadio,
            Role::MenuListPopup => PyRole::MenuListPopup,
            Role::Meter => PyRole::Meter,
            Role::Navigation => PyRole::Navigation,
            Role::Note => PyRole::Note,
            Role::PluginObject => PyRole::PluginObject,
            Role::ProgressIndicator => PyRole::ProgressIndicator,
            Role::RadioGroup => PyRole::RadioGroup,
            Role::Region => PyRole::Region,
            Role::RootWebArea => PyRole::RootWebArea,
            Role::Ruby => PyRole::Ruby,
            Role::RubyAnnotation => PyRole::RubyAnnotation,
            Role::ScrollBar => PyRole::ScrollBar,
            Role::ScrollView => PyRole::ScrollView,
            Role::Search => PyRole::Search,
            Role::Section => PyRole::Section,
            Role::SectionFooter => PyRole::SectionFooter,
            Role::SectionHeader => PyRole::SectionHeader,
            Role::Slider => PyRole::Slider,
            Role::SpinButton => PyRole::SpinButton,
            Role::Splitter => PyRole::Splitter,
            Role::Status => PyRole::Status,
            Role::Strong => PyRole::Strong,
            Role::Suggestion => PyRole::Suggestion,
            Role::SvgRoot => PyRole::SvgRoot,
            Role::Tab => PyRole::Tab,
            Role::TabList => PyRole::TabList,
            Role::TabPanel => PyRole::TabPanel,
            Role::Term => PyRole::Term,
            Role::Time => PyRole::Time,
            Role::Timer => PyRole::Timer,
            Role::TitleBar => PyRole::TitleBar,
            Role::Toolbar => PyRole::Toolbar,
            Role::Tooltip => PyRole::Tooltip,
            Role::Tree => PyRole::Tree,
            Role::TreeGrid => PyRole::TreeGrid,
            Role::Video => PyRole::Video,
            Role::WebView => PyRole::WebView,
            Role::Window => PyRole::Window,
            Role::PdfActionableHighlight => PyRole::PdfActionableHighlight,
            Role::PdfRoot => PyRole::PdfRoot,
            Role::GraphicsDocument => PyRole::GraphicsDocument,
            Role::GraphicsObject => PyRole::GraphicsObject,
            Role::GraphicsSymbol => PyRole::GraphicsSymbol,
            Role::DocAbstract => PyRole::DocAbstract,
            Role::DocAcknowledgements => PyRole::DocAcknowledgements,
            Role::DocAfterword => PyRole::DocAfterword,
            Role::DocAppendix => PyRole::DocAppendix,
            Role::DocBackLink => PyRole::DocBackLink,
            Role::DocBiblioEntry => PyRole::DocBiblioEntry,
            Role::DocBibliography => PyRole::DocBibliography,
            Role::DocBiblioRef => PyRole::DocBiblioRef,
            Role::DocChapter => PyRole::DocChapter,
            Role::DocColophon => PyRole::DocColophon,
            Role::DocConclusion => PyRole::DocConclusion,
            Role::DocCover => PyRole::DocCover,
            Role::DocCredit => PyRole::DocCredit,
            Role::DocCredits => PyRole::DocCredits,
            Role::DocDedication => PyRole::DocDedication,
            Role::DocEndnote => PyRole::DocEndnote,
            Role::DocEndnotes => PyRole::DocEndnotes,
            Role::DocEpigraph => PyRole::DocEpigraph,
            Role::DocEpilogue => PyRole::DocEpilogue,
            Role::DocErrata => PyRole::DocErrata,
            Role::DocExample => PyRole::DocExample,
            Role::DocFootnote => PyRole::DocFootnote,
            Role::DocForeword => PyRole::DocForeword,
            Role::DocGlossary => PyRole::DocGlossary,
            Role::DocGlossRef => PyRole::DocGlossRef,
            Role::DocIndex => PyRole::DocIndex,
            Role::DocIntroduction => PyRole::DocIntroduction,
            Role::DocNoteRef => PyRole::DocNoteRef,
            Role::DocNotice => PyRole::DocNotice,
            Role::DocPageBreak => PyRole::DocPageBreak,
            Role::DocPageFooter => PyRole::DocPageFooter,
            Role::DocPageHeader => PyRole::DocPageHeader,
            Role::DocPageList => PyRole::DocPageList,
            Role::DocPart => PyRole::DocPart,
            Role::DocPreface => PyRole::DocPreface,
            Role::DocPrologue => PyRole::DocPrologue,
            Role::DocPullquote => PyRole::DocPullquote,
            Role::DocQna => PyRole::DocQna,
            Role::DocSubtitle => PyRole::DocSubtitle,
            Role::DocTip => PyRole::DocTip,
            Role::DocToc => PyRole::DocToc,
            Role::ListGrid => PyRole::ListGrid,
            Role::Terminal => PyRole::Terminal,
        }
    }
}
