//! Message bridge trait for runtime type dispatch
//!
//! This module provides the `MessageBridge` trait that allows feature crates
//! to register their Bevy message types without the core crate needing to import them.
//!
//! # Pattern
//!
//! 1. Feature crate implements `MessageBridge` for each message type
//! 2. Feature crate's plugin registers bridges at startup
//! 3. Core uses bridges via runtime dispatch (no compile-time coupling)
//!
//! This replaces the hard-coded if-chain in `PyMessageType::from_message_type()`
//! with dynamic dispatch via the global registry.

use std::any::{Any, TypeId};

use bevy::ecs::{component::ComponentId, world::World};
use pyo3::{ffi::PyTypeObject, prelude::*, types::PyType};

/// Trait that bridges a Bevy message type to its Python wrapper.
///
/// Each feature crate implements this for its message types. The trait provides
/// all the methods needed for:
/// - Type identification (Rust TypeId, Python type object)
/// - Message iteration (reading from Messages<T>)
/// - Message writing (if applicable)
///
/// # Read-Only Messages
///
/// Most input events (keyboard, mouse, gamepad) are read-only - they're generated
/// by Bevy's input systems. Only custom messages and some special types (AppExit)
/// can be written from Python.
pub trait MessageBridge: Send + Sync + 'static {
    /// Rust TypeId of the Bevy message type
    fn bevy_type_id(&self) -> TypeId;

    /// Python type object pointer for type matching
    ///
    /// Used for O(1) lookup in HashMap when dispatching from Python types.
    fn py_type_ptr(&self) -> *const PyTypeObject;

    /// Get Python type object
    fn py_type<'py>(&self, py: Python<'py>) -> Bound<'py, PyType>;

    /// Human-readable name for error messages
    fn name(&self) -> &'static str;

    /// Whether this message type is read-only (cannot be written from Python)
    ///
    /// Returns true for input events that are generated by Bevy's systems.
    /// Returns false for custom messages and AppExit.
    fn is_read_only(&self) -> bool {
        true // Default to read-only for safety
    }

    /// Iterate messages from the world and convert to Python objects.
    /// Creates a fresh cursor each time (reads all buffered messages).
    fn iter_to_python(&self, py: Python, world: &mut World) -> PyResult<Vec<Py<PyAny>>>;

    /// Iterate messages using a persistent cursor to avoid re-reading.
    ///
    /// The cursor state is stored in `cursor_storage` between calls.
    /// On first call (when cursor_storage is None), reads all buffered messages.
    /// On subsequent calls, only reads messages written since the last read.
    ///
    /// Default implementation falls back to `iter_to_python` (fresh cursor).
    fn iter_to_python_with_cursor(
        &self,
        py: Python,
        world: &mut World,
        cursor_storage: &mut Option<Box<dyn Any + Send + Sync>>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let _ = cursor_storage; // Default ignores cursor storage
        self.iter_to_python(py, world)
    }

    /// Write a message to the world
    fn write_message(
        &self,
        _py: Python,
        _world: &mut World,
        _message: &Bound<'_, PyAny>,
    ) -> PyResult<Box<dyn std::any::Any + Send + Sync>> {
        Err(pyo3::exceptions::PyTypeError::new_err(format!(
            "{} messages are read-only (generated by system)",
            self.name()
        )))
    }

    /// Clear all messages of this type
    fn clear(&self, world: &mut World) -> PyResult<()>;

    /// Check if there are no messages of this type
    fn is_empty(&self, world: &mut World) -> PyResult<bool>;

    /// Get the number of messages of this type
    fn len(&self, world: &mut World) -> PyResult<usize>;

    /// Get the ComponentId for the Messages<T> resource in the world
    ///
    /// Used by system access declaration to register read/write access.
    fn resource_id(&self, world: &World) -> Option<ComponentId>;

    /// Register (get-or-create) the ComponentId for the `Messages<T>` resource.
    ///
    /// Unlike `resource_id`, this never returns None: it creates the id when the
    /// `Messages<T>` resource is absent so `DynamicSystem::initialize` can declare
    /// access even before the message type's first write. The created id is
    /// TypeId-keyed and equals the one a later insertion resolves to.
    fn register_resource_id(&self, world: &mut World) -> ComponentId;
}
