//! Message bridge trait for runtime type dispatch
//!
//! This module provides the `MessageBridge` trait that allows feature crates
//! to register their Bevy message types without the core crate needing to import them.
//!
//! # Pattern
//!
//! 1. Feature crate implements `MessageBridge` for each message type
//! 2. Feature crate's plugin registers bridges at startup
//! 3. Core uses bridges via runtime dispatch (no compile-time coupling)
//!
//! This replaces the hard-coded if-chain in `PyMessageType::from_message_type()`
//! with dynamic dispatch via the global registry.

use std::any::{Any, TypeId};

use bevy::ecs::{component::ComponentId, world::World};
use pyo3::{ffi::PyTypeObject, prelude::*, types::PyType};

/// Trait that bridges a Bevy message type to its Python wrapper.
///
/// Each feature crate implements this for its message types. The trait provides
/// all the methods needed for:
/// - Type identification (Rust TypeId, Python type object)
/// - Message iteration (reading from Messages<T>)
/// - Message writing (if applicable)
///
/// # Read-Only Messages
///
/// Most input events (keyboard, mouse, gamepad) are read-only - they're generated
/// by Bevy's input systems. Only custom messages and some special types (AppExit)
/// can be written from Python.
pub trait MessageBridge: Send + Sync + 'static {
    /// Rust TypeId of the Bevy message type
    fn bevy_type_id(&self) -> TypeId;

    /// Python type object pointer for type matching
    ///
    /// Used for O(1) lookup in HashMap when dispatching from Python types.
    fn py_type_ptr(&self) -> *const PyTypeObject;

    /// Get Python type object
    fn py_type<'py>(&self, py: Python<'py>) -> Bound<'py, PyType>;

    /// Human-readable name for error messages
    fn name(&self) -> &'static str;

    /// Whether this message type is read-only (cannot be written from Python)
    ///
    /// Returns true for input events that are generated by Bevy's systems.
    /// Returns false for custom messages and AppExit.
    fn is_read_only(&self) -> bool {
        true // Default to read-only for safety
    }

    /// Iterate messages from the world and convert to Python objects.
    /// Creates a fresh cursor each time (reads all buffered messages).
    fn iter_to_python(&self, py: Python, world: &mut World) -> PyResult<Vec<Py<PyAny>>>;

    /// Iterate messages using a persistent cursor to avoid re-reading.
    ///
    /// The cursor state is stored in `cursor_storage` between calls.
    /// On first call (when cursor_storage is None), reads all buffered messages.
    /// On subsequent calls, only reads messages written since the last read.
    ///
    /// Default implementation falls back to `iter_to_python` (fresh cursor).
    fn iter_to_python_with_cursor(
        &self,
        py: Python,
        world: &mut World,
        cursor_storage: &mut Option<Box<dyn Any + Send + Sync>>,
    ) -> PyResult<Vec<Py<PyAny>>> {
        let _ = cursor_storage; // Default ignores cursor storage
        self.iter_to_python(py, world)
    }

    /// Write a message to the world
    fn write_message(
        &self,
        _py: Python,
        _world: &mut World,
        _message: &Bound<'_, PyAny>,
    ) -> PyResult<Box<dyn std::any::Any + Send + Sync>> {
        Err(pyo3::exceptions::PyTypeError::new_err(format!(
            "{} messages are read-only (generated by system)",
            self.name()
        )))
    }

    /// Clear all messages of this type
    fn clear(&self, world: &mut World) -> PyResult<()>;

    /// Check if there are no messages of this type
    fn is_empty(&self, world: &mut World) -> PyResult<bool>;

    /// Get the number of messages of this type
    fn len(&self, world: &mut World) -> PyResult<usize>;

    /// Get the ComponentId for the Messages<T> resource in the world
    ///
    /// Used by system access declaration to register read/write access.
    fn resource_id(&self, world: &World) -> Option<ComponentId>;

    /// Register (get-or-create) the ComponentId for the `Messages<T>` resource.
    ///
    /// Unlike `resource_id`, this never returns None: it creates the id when the
    /// `Messages<T>` resource is absent so `DynamicSystem::initialize` can declare
    /// access even before the message type's first write. The created id is
    /// TypeId-keyed and equals the one a later insertion resolves to.
    fn register_resource_id(&self, world: &mut World) -> ComponentId;
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use std::{
        any::{Any, TypeId},
        sync::atomic::{AtomicUsize, Ordering},
    };

    use bevy::ecs::component::ComponentId;
    use pyo3::{
        exceptions::PyTypeError,
        ffi::PyTypeObject,
        prelude::*,
        types::{PyInt, PyType},
    };

    use super::*;

    const FAKE_PTR: usize = 0x7201;
    static FRESH_READS: AtomicUsize = AtomicUsize::new(0);

    // Implements only the required methods: is_read_only, iter_to_python_with_cursor
    // and write_message stay on their trait defaults.
    struct DefaultMessageBridge {
        name: &'static str,
    }

    impl MessageBridge for DefaultMessageBridge {
        fn bevy_type_id(&self) -> TypeId {
            TypeId::of::<DefaultMessageBridge>()
        }

        fn py_type_ptr(&self) -> *const PyTypeObject {
            FAKE_PTR as *const PyTypeObject
        }

        fn py_type<'py>(&self, _py: Python<'py>) -> Bound<'py, PyType> {
            unreachable!("default-methods-only fake bridge")
        }

        fn name(&self) -> &'static str {
            self.name
        }

        fn iter_to_python(&self, py: Python, _world: &mut World) -> PyResult<Vec<Py<PyAny>>> {
            let read = FRESH_READS.fetch_add(1, Ordering::SeqCst) + 1;
            Ok(vec![PyInt::new(py, read).into()])
        }

        fn clear(&self, _world: &mut World) -> PyResult<()> {
            Ok(())
        }

        fn is_empty(&self, _world: &mut World) -> PyResult<bool> {
            Ok(true)
        }

        fn len(&self, _world: &mut World) -> PyResult<usize> {
            Ok(0)
        }

        fn resource_id(&self, _world: &World) -> Option<ComponentId> {
            None
        }

        fn register_resource_id(&self, _world: &mut World) -> ComponentId {
            ComponentId::new(0)
        }
    }

    #[test]
    fn default_is_read_only_is_true() {
        let bridge = DefaultMessageBridge {
            name: "DefaultFakeMessage",
        };
        assert!(
            bridge.is_read_only(),
            "un-overridden bridge must default to read-only"
        );
    }

    #[test]
    fn default_write_message_reports_the_bridge_name() {
        let bridge = DefaultMessageBridge {
            name: "DefaultFakeMessage",
        };

        Python::attach(|py| {
            let mut world = World::new();
            let message = py.None();
            let error = bridge
                .write_message(py, &mut world, message.bind(py))
                .unwrap_err();
            assert!(
                error.is_instance_of::<PyTypeError>(py),
                "the default write_message must raise TypeError"
            );
            // Pin the exact user-visible message (Python `str(exc)`).
            assert_eq!(
                error.value(py).str().unwrap().to_string(),
                "DefaultFakeMessage messages are read-only (generated by system)"
            );
        });
    }

    #[test]
    fn default_cursor_iteration_falls_back_to_the_fresh_cursor() {
        let bridge = DefaultMessageBridge {
            name: "DefaultFakeMessage",
        };
        let before = FRESH_READS.load(Ordering::SeqCst);
        let mut storage: Option<Box<dyn Any + Send + Sync>> = None;

        Python::attach(|py| {
            let mut world = World::new();
            let first = bridge
                .iter_to_python_with_cursor(py, &mut world, &mut storage)
                .unwrap();
            let second = bridge
                .iter_to_python_with_cursor(py, &mut world, &mut storage)
                .unwrap();
            assert_eq!(first.len(), 1);
            assert_eq!(second.len(), 1);
            // Each call performs one fresh read: the counter-backed values advance.
            assert_eq!(
                first[0].extract::<i64>(py).unwrap(),
                i64::try_from(before).unwrap() + 1
            );
            assert_eq!(
                second[0].extract::<i64>(py).unwrap(),
                i64::try_from(before).unwrap() + 2
            );
        });

        assert!(
            storage.is_none(),
            "the default leaves cursor storage untouched"
        );
        assert_eq!(FRESH_READS.load(Ordering::SeqCst), before + 2);
    }
}
