//! Batch component type for Rust-side components (e.g., PointLight, SpotLight).
//!
//! `PyRustComponentBatch` stores a component type pointer plus normalized field
//! columns. The actual insertion is delegated to a macro-generated typed
//! function via `ComponentBatchMeta`.

use std::{collections::HashMap, sync::Arc};

use bevy::ecs::{entity::Entity, world::World};
use pyo3::{
    exceptions::PyValueError,
    prelude::*,
    types::{PyDict, PyList, PyTuple},
};

use super::{
    batch_bridge::{BatchComponent, PreparedBatchComponent},
    global_registry,
};

/// Batch component for Rust-side components (auto-generated by macro).
///
/// Created via `PointLight.batch(intensity=intensities, range=ranges)`.
/// External NumPy inputs retain their normalized arrays. Portable Python
/// sequences and bounded arrays are snapshotted into owned f32 columns.
#[pyclass(name = "RustComponentBatch")]
pub struct PyRustComponentBatch {
    /// Pointer to the component's Python type (for registry lookup)
    pub component_type_ptr: usize,
    /// Field name → numpy array (stored as Py<PyAny>)
    pub field_arrays: HashMap<String, Py<PyAny>>,
    /// Field name → owned contiguous f32 values for dependency-free inputs.
    pub field_values: HashMap<String, Vec<f32>>,
    /// Number of entities to spawn
    pub count: usize,
    /// Component name for error messages
    pub component_name: String,
}

#[pymethods]
impl PyRustComponentBatch {
    /// Get the number of entities in this batch
    fn __len__(&self) -> usize {
        self.count
    }

    /// The Batchable protocol's method. Same number as `len()`.
    fn count(&self) -> usize {
        self.count
    }
}

impl PyRustComponentBatch {
    /// Get a field array by name, bound to the current Python context.
    pub fn get_field_array<'py>(&self, py: Python<'py>, name: &str) -> Option<Bound<'py, PyAny>> {
        self.field_arrays.get(name).map(|a| a.bind(py).clone())
    }

    /// Get an owned portable field column by name.
    pub fn get_field_values(&self, name: &str) -> Option<&[f32]> {
        self.field_values.get(name).map(Vec::as_slice)
    }
}

/// Snapshot a plain sequence or bounded array as an owned contiguous f32 column.
///
/// External arrays return `None` so the existing NumPy adapter remains their
/// normalization path. The bounded-array converter holds all validity and
/// storage guards for the complete synchronous copy.
pub fn portable_f32_batch_column(
    value: &Bound<'_, PyAny>,
) -> PyResult<Option<(Vec<usize>, Vec<f32>)>> {
    let is_sequence = value.is_instance_of::<PyList>() || value.is_instance_of::<PyTuple>();
    let array_module = value.py().import("pybevy.array")?;
    let is_bounded_array = value.is_instance(&array_module.getattr("Array")?)?;
    if !is_sequence && !is_bounded_array {
        return Ok(None);
    }

    let kwargs = PyDict::new(value.py());
    kwargs.set_item("dtype", array_module.getattr("float32")?)?;
    let normalized = array_module
        .getattr("asarray")?
        .call((value,), Some(&kwargs))?;
    let shape = normalized.getattr("shape")?.extract()?;
    let values = normalized
        .call_method0("ravel")?
        .call_method0("tolist")?
        .extract()?;
    Ok(Some((shape, values)))
}

/// Bridge for RustComponentBatch that implements BatchComponent.
pub struct RustComponentBatchBridge;

impl BatchComponent for RustComponentBatchBridge {
    fn name(&self) -> &'static str {
        "RustComponentBatch"
    }

    fn component_type_ptr(&self, _py: Python, batch: &Bound<PyAny>) -> PyResult<usize> {
        Ok(batch
            .extract::<PyRef<PyRustComponentBatch>>()?
            .component_type_ptr)
    }

    fn count(&self, _py: Python, batch: &Bound<PyAny>) -> PyResult<usize> {
        let batch = batch.extract::<PyRef<PyRustComponentBatch>>()?;
        Ok(batch.count)
    }

    fn prepare(
        &self,
        py: Python,
        batch: &Bound<PyAny>,
    ) -> PyResult<Box<dyn PreparedBatchComponent>> {
        let batch = batch.extract::<PyRef<PyRustComponentBatch>>()?;
        let meta = global_registry::get_component_batch_meta(batch.component_type_ptr).ok_or_else(
            || {
                PyValueError::new_err(format!(
                    "No batch metadata registered for component '{}' (type ptr: 0x{:x})",
                    batch.component_name, batch.component_type_ptr
                ))
            },
        )?;
        (meta.prepare_fn)(py, &batch)
    }

    fn insert_bulk(
        &self,
        py: Python,
        batch: &Bound<PyAny>,
        entities: &[Entity],
        world: &mut World,
    ) -> PyResult<()> {
        let batch = batch.extract::<PyRef<PyRustComponentBatch>>()?;

        // Look up the ComponentBatchMeta for this component type
        let meta = global_registry::get_component_batch_meta(batch.component_type_ptr).ok_or_else(
            || {
                PyValueError::new_err(format!(
                    "No batch metadata registered for component '{}' (type ptr: 0x{:x})",
                    batch.component_name, batch.component_type_ptr
                ))
            },
        )?;

        // Delegate to macro-generated insert function
        (meta.insert_fn)(py, &batch, entities, world)
    }
}

/// Register the RustComponentBatch bridge so spawn_batch can detect it.
pub fn register_rust_batch_bridge() {
    Python::attach(|py| {
        let ptr = <PyRustComponentBatch as pyo3::PyTypeInfo>::type_object(py).as_type_ptr();
        global_registry::register_batch_bridge(ptr, Arc::new(RustComponentBatchBridge));
    });
}
