//! Batch component type for Rust-side components (e.g., PointLight, SpotLight).
//!
//! `PyRustComponentBatch` stores a component type pointer and field name → numpy array map.
//! The actual insertion is delegated to a macro-generated typed function via `ComponentBatchMeta`.

use std::{collections::HashMap, sync::Arc};

use bevy::ecs::{entity::Entity, world::World};
use pyo3::{exceptions::PyValueError, prelude::*};

use super::{
    batch_bridge::{BatchComponent, PreparedBatchComponent},
    global_registry,
};

/// Batch component for Rust-side components (auto-generated by macro).
///
/// Created via `PointLight.from_numpy(intensity=intensities, range=ranges)`.
/// Stores numpy arrays as `Py<PyAny>`: no numpy Rust bindings in pybevy_core.
/// Array normalization happens at construction via Python-level numpy calls.
#[pyclass(name = "RustComponentBatch")]
pub struct PyRustComponentBatch {
    /// Pointer to the component's Python type (for registry lookup)
    pub component_type_ptr: usize,
    /// Field name → numpy array (stored as Py<PyAny>)
    pub field_arrays: HashMap<String, Py<PyAny>>,
    /// Number of entities to spawn
    pub count: usize,
    /// Component name for error messages
    pub component_name: String,
}

#[pymethods]
impl PyRustComponentBatch {
    /// Get the number of entities in this batch
    fn __len__(&self) -> usize {
        self.count
    }
}

impl PyRustComponentBatch {
    /// Get a field array by name, bound to the current Python context.
    pub fn get_field_array<'py>(&self, py: Python<'py>, name: &str) -> Option<Bound<'py, PyAny>> {
        self.field_arrays.get(name).map(|a| a.bind(py).clone())
    }
}

/// Bridge for RustComponentBatch that implements BatchComponent.
pub struct RustComponentBatchBridge;

impl BatchComponent for RustComponentBatchBridge {
    fn name(&self) -> &'static str {
        "RustComponentBatch"
    }

    fn component_type_ptr(&self, _py: Python, batch: &Bound<PyAny>) -> PyResult<usize> {
        Ok(batch
            .extract::<PyRef<PyRustComponentBatch>>()?
            .component_type_ptr)
    }

    fn count(&self, _py: Python, batch: &Bound<PyAny>) -> PyResult<usize> {
        let batch = batch.extract::<PyRef<PyRustComponentBatch>>()?;
        Ok(batch.count)
    }

    fn prepare(
        &self,
        py: Python,
        batch: &Bound<PyAny>,
    ) -> PyResult<Box<dyn PreparedBatchComponent>> {
        let batch = batch.extract::<PyRef<PyRustComponentBatch>>()?;
        let meta = global_registry::get_component_batch_meta(batch.component_type_ptr).ok_or_else(
            || {
                PyValueError::new_err(format!(
                    "No batch metadata registered for component '{}' (type ptr: 0x{:x})",
                    batch.component_name, batch.component_type_ptr
                ))
            },
        )?;
        (meta.prepare_fn)(py, &batch)
    }

    fn insert_bulk(
        &self,
        py: Python,
        batch: &Bound<PyAny>,
        entities: &[Entity],
        world: &mut World,
    ) -> PyResult<()> {
        let batch = batch.extract::<PyRef<PyRustComponentBatch>>()?;

        // Look up the ComponentBatchMeta for this component type
        let meta = global_registry::get_component_batch_meta(batch.component_type_ptr).ok_or_else(
            || {
                PyValueError::new_err(format!(
                    "No batch metadata registered for component '{}' (type ptr: 0x{:x})",
                    batch.component_name, batch.component_type_ptr
                ))
            },
        )?;

        // Delegate to macro-generated insert function
        (meta.insert_fn)(py, &batch, entities, world)
    }
}

/// Register the RustComponentBatch bridge so spawn_batch can detect it.
pub fn register_rust_batch_bridge() {
    Python::attach(|py| {
        let ptr = <PyRustComponentBatch as pyo3::PyTypeInfo>::type_object(py).as_type_ptr();
        global_registry::register_batch_bridge(ptr, Arc::new(RustComponentBatchBridge));
    });
}
