[package]
name = "pybevy_time"
version = "0.3.0"
edition = "2024"
description = "Time resources for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_macros = { workspace = true }
pybevy_core = { workspace = true }

[dependencies.bevy]
workspace = true
features = []

[lints]
workspace = true
