[package]
name = "pybevy_a11y"
version = "0.3.0"
edition = "2024"
description = "Accessibility components for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
accesskit = { version = "0.24", default-features = false }

[dependencies.bevy]
workspace = true
default-features = false
features = ["bevy_window"]

[lints]
workspace = true
