[package]
name = "pybevy_animation"
version = "0.2.1"
edition = "2024"
description = "Animation types for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
uuid = { workspace = true }
pybevy_core = { path = "../pybevy_core", version = "=0.2.1" }
pybevy_macros = { path = "../pybevy_macros", version = "=0.2.1" }
pybevy_mesh = { workspace = true }

[dependencies.bevy]
workspace = true
features = ["gltf_animation", "bevy_render", "bevy_animation"]

[lints]
workspace = true
