[package]
name = "pybevy_render"
version = "0.2.1"
edition = "2024"
description = "Render and wgpu types for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true }
bevy = { workspace = true, features = [
    "bevy_render", "bevy_pbr",
    # Image formats
    "png", "jpeg", "bmp", "tga", "webp", "tiff", "pnm", "qoi", "hdr", "dds", "ktx2"
] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_shader = { workspace = true }
pybevy_wgpu = { workspace = true }
pybevy_image = { workspace = true }
pybevy_color = { workspace = true }
pybevy_math = { workspace = true }
wgpu-types = "29"
wgpu = { version = "29", default-features = false }
tracing = "0.1"
crossbeam-channel = "0.5"

[lints]
workspace = true
