use bevy::render::render_resource::TextureFormat;
use pybevy_core::public_error::unsupported_texture_format;
use pyo3::{exceptions::PyValueError, prelude::*};

#[pyclass(name = "TextureFormat", eq, frozen, from_py_object)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PyTextureFormat {
    R8Unorm,
    R8Snorm,
    R8Uint,
    R8Sint,
    R16Uint,
    R16Sint,
    R16Unorm,
    R16Snorm,
    R16Float,
    Rg8Unorm,
    Rg8Snorm,
    Rg8Uint,
    Rg8Sint,
    R32Uint,
    R32Sint,
    R32Float,
    Rg16Uint,
    Rg16Sint,
    Rg16Unorm,
    Rg16Snorm,
    Rg16Float,
    Rgba8Unorm,
    Rgba8UnormSrgb,
    Rgba8Snorm,
    Rgba8Uint,
    Rgba8Sint,
    Bgra8Unorm,
    Bgra8UnormSrgb,
    Rgb9e5Ufloat,
    Rgb10a2Uint,
    Rgb10a2Unorm,
    Rg11b10Ufloat,
    R64Uint,
    Rg32Uint,
    Rg32Sint,
    Rg32Float,
    Rgba16Uint,
    Rgba16Sint,
    Rgba16Unorm,
    Rgba16Snorm,
    Rgba16Float,
    Rgba32Uint,
    Rgba32Sint,
    Rgba32Float,
    Stencil8,
    Depth16Unorm,
    Depth24Plus,
    Depth24PlusStencil8,
    Depth32Float,
    Depth32FloatStencil8,
    NV12,
    P010,
    Bc1RgbaUnorm,
    Bc1RgbaUnormSrgb,
    Bc2RgbaUnorm,
    Bc2RgbaUnormSrgb,
    Bc3RgbaUnorm,
    Bc3RgbaUnormSrgb,
    Bc4RUnorm,
    Bc4RSnorm,
    Bc5RgUnorm,
    Bc5RgSnorm,
    Bc6hRgbUfloat,
    Bc6hRgbFloat,
    Bc7RgbaUnorm,
    Bc7RgbaUnormSrgb,
    Etc2Rgb8Unorm,
    Etc2Rgb8UnormSrgb,
    Etc2Rgb8A1Unorm,
    Etc2Rgb8A1UnormSrgb,
    Etc2Rgba8Unorm,
    Etc2Rgba8UnormSrgb,
    EacR11Unorm,
    EacR11Snorm,
    EacRg11Unorm,
    EacRg11Snorm,
}

impl From<PyTextureFormat> for TextureFormat {
    fn from(format: PyTextureFormat) -> Self {
        match format {
            PyTextureFormat::R8Unorm => TextureFormat::R8Unorm,
            PyTextureFormat::R8Snorm => TextureFormat::R8Snorm,
            PyTextureFormat::R8Uint => TextureFormat::R8Uint,
            PyTextureFormat::R8Sint => TextureFormat::R8Sint,
            PyTextureFormat::R16Uint => TextureFormat::R16Uint,
            PyTextureFormat::R16Sint => TextureFormat::R16Sint,
            PyTextureFormat::R16Unorm => TextureFormat::R16Unorm,
            PyTextureFormat::R16Snorm => TextureFormat::R16Snorm,
            PyTextureFormat::R16Float => TextureFormat::R16Float,
            PyTextureFormat::Rg8Unorm => TextureFormat::Rg8Unorm,
            PyTextureFormat::Rg8Snorm => TextureFormat::Rg8Snorm,
            PyTextureFormat::Rg8Uint => TextureFormat::Rg8Uint,
            PyTextureFormat::Rg8Sint => TextureFormat::Rg8Sint,
            PyTextureFormat::R32Uint => TextureFormat::R32Uint,
            PyTextureFormat::R32Sint => TextureFormat::R32Sint,
            PyTextureFormat::R32Float => TextureFormat::R32Float,
            PyTextureFormat::Rg16Uint => TextureFormat::Rg16Uint,
            PyTextureFormat::Rg16Sint => TextureFormat::Rg16Sint,
            PyTextureFormat::Rg16Unorm => TextureFormat::Rg16Unorm,
            PyTextureFormat::Rg16Snorm => TextureFormat::Rg16Snorm,
            PyTextureFormat::Rg16Float => TextureFormat::Rg16Float,
            PyTextureFormat::Rgba8Unorm => TextureFormat::Rgba8Unorm,
            PyTextureFormat::Rgba8UnormSrgb => TextureFormat::Rgba8UnormSrgb,
            PyTextureFormat::Rgba8Snorm => TextureFormat::Rgba8Snorm,
            PyTextureFormat::Rgba8Uint => TextureFormat::Rgba8Uint,
            PyTextureFormat::Rgba8Sint => TextureFormat::Rgba8Sint,
            PyTextureFormat::Bgra8Unorm => TextureFormat::Bgra8Unorm,
            PyTextureFormat::Bgra8UnormSrgb => TextureFormat::Bgra8UnormSrgb,
            PyTextureFormat::Rgb9e5Ufloat => TextureFormat::Rgb9e5Ufloat,
            PyTextureFormat::Rgb10a2Uint => TextureFormat::Rgb10a2Uint,
            PyTextureFormat::Rgb10a2Unorm => TextureFormat::Rgb10a2Unorm,
            PyTextureFormat::Rg11b10Ufloat => TextureFormat::Rg11b10Ufloat,
            PyTextureFormat::R64Uint => TextureFormat::R64Uint,
            PyTextureFormat::Rg32Uint => TextureFormat::Rg32Uint,
            PyTextureFormat::Rg32Sint => TextureFormat::Rg32Sint,
            PyTextureFormat::Rg32Float => TextureFormat::Rg32Float,
            PyTextureFormat::Rgba16Uint => TextureFormat::Rgba16Uint,
            PyTextureFormat::Rgba16Sint => TextureFormat::Rgba16Sint,
            PyTextureFormat::Rgba16Unorm => TextureFormat::Rgba16Unorm,
            PyTextureFormat::Rgba16Snorm => TextureFormat::Rgba16Snorm,
            PyTextureFormat::Rgba16Float => TextureFormat::Rgba16Float,
            PyTextureFormat::Rgba32Uint => TextureFormat::Rgba32Uint,
            PyTextureFormat::Rgba32Sint => TextureFormat::Rgba32Sint,
            PyTextureFormat::Rgba32Float => TextureFormat::Rgba32Float,
            PyTextureFormat::Stencil8 => TextureFormat::Stencil8,
            PyTextureFormat::Depth16Unorm => TextureFormat::Depth16Unorm,
            PyTextureFormat::Depth24Plus => TextureFormat::Depth24Plus,
            PyTextureFormat::Depth24PlusStencil8 => TextureFormat::Depth24PlusStencil8,
            PyTextureFormat::Depth32Float => TextureFormat::Depth32Float,
            PyTextureFormat::Depth32FloatStencil8 => TextureFormat::Depth32FloatStencil8,
            PyTextureFormat::NV12 => TextureFormat::NV12,
            PyTextureFormat::P010 => TextureFormat::P010,
            PyTextureFormat::Bc1RgbaUnorm => TextureFormat::Bc1RgbaUnorm,
            PyTextureFormat::Bc1RgbaUnormSrgb => TextureFormat::Bc1RgbaUnormSrgb,
            PyTextureFormat::Bc2RgbaUnorm => TextureFormat::Bc2RgbaUnorm,
            PyTextureFormat::Bc2RgbaUnormSrgb => TextureFormat::Bc2RgbaUnormSrgb,
            PyTextureFormat::Bc3RgbaUnorm => TextureFormat::Bc3RgbaUnorm,
            PyTextureFormat::Bc3RgbaUnormSrgb => TextureFormat::Bc3RgbaUnormSrgb,
            PyTextureFormat::Bc4RUnorm => TextureFormat::Bc4RUnorm,
            PyTextureFormat::Bc4RSnorm => TextureFormat::Bc4RSnorm,
            PyTextureFormat::Bc5RgUnorm => TextureFormat::Bc5RgUnorm,
            PyTextureFormat::Bc5RgSnorm => TextureFormat::Bc5RgSnorm,
            PyTextureFormat::Bc6hRgbUfloat => TextureFormat::Bc6hRgbUfloat,
            PyTextureFormat::Bc6hRgbFloat => TextureFormat::Bc6hRgbFloat,
            PyTextureFormat::Bc7RgbaUnorm => TextureFormat::Bc7RgbaUnorm,
            PyTextureFormat::Bc7RgbaUnormSrgb => TextureFormat::Bc7RgbaUnormSrgb,
            PyTextureFormat::Etc2Rgb8Unorm => TextureFormat::Etc2Rgb8Unorm,
            PyTextureFormat::Etc2Rgb8UnormSrgb => TextureFormat::Etc2Rgb8UnormSrgb,
            PyTextureFormat::Etc2Rgb8A1Unorm => TextureFormat::Etc2Rgb8A1Unorm,
            PyTextureFormat::Etc2Rgb8A1UnormSrgb => TextureFormat::Etc2Rgb8A1UnormSrgb,
            PyTextureFormat::Etc2Rgba8Unorm => TextureFormat::Etc2Rgba8Unorm,
            PyTextureFormat::Etc2Rgba8UnormSrgb => TextureFormat::Etc2Rgba8UnormSrgb,
            PyTextureFormat::EacR11Unorm => TextureFormat::EacR11Unorm,
            PyTextureFormat::EacR11Snorm => TextureFormat::EacR11Snorm,
            PyTextureFormat::EacRg11Unorm => TextureFormat::EacRg11Unorm,
            PyTextureFormat::EacRg11Snorm => TextureFormat::EacRg11Snorm,
        }
    }
}

impl TryFrom<TextureFormat> for PyTextureFormat {
    type Error = PyErr;

    fn try_from(format: TextureFormat) -> Result<Self, Self::Error> {
        Ok(match format {
            TextureFormat::R8Unorm => PyTextureFormat::R8Unorm,
            TextureFormat::R8Snorm => PyTextureFormat::R8Snorm,
            TextureFormat::R8Uint => PyTextureFormat::R8Uint,
            TextureFormat::R8Sint => PyTextureFormat::R8Sint,
            TextureFormat::R16Uint => PyTextureFormat::R16Uint,
            TextureFormat::R16Sint => PyTextureFormat::R16Sint,
            TextureFormat::R16Unorm => PyTextureFormat::R16Unorm,
            TextureFormat::R16Snorm => PyTextureFormat::R16Snorm,
            TextureFormat::R16Float => PyTextureFormat::R16Float,
            TextureFormat::Rg8Unorm => PyTextureFormat::Rg8Unorm,
            TextureFormat::Rg8Snorm => PyTextureFormat::Rg8Snorm,
            TextureFormat::Rg8Uint => PyTextureFormat::Rg8Uint,
            TextureFormat::Rg8Sint => PyTextureFormat::Rg8Sint,
            TextureFormat::R32Uint => PyTextureFormat::R32Uint,
            TextureFormat::R32Sint => PyTextureFormat::R32Sint,
            TextureFormat::R32Float => PyTextureFormat::R32Float,
            TextureFormat::Rg16Uint => PyTextureFormat::Rg16Uint,
            TextureFormat::Rg16Sint => PyTextureFormat::Rg16Sint,
            TextureFormat::Rg16Unorm => PyTextureFormat::Rg16Unorm,
            TextureFormat::Rg16Snorm => PyTextureFormat::Rg16Snorm,
            TextureFormat::Rg16Float => PyTextureFormat::Rg16Float,
            TextureFormat::Rgba8Unorm => PyTextureFormat::Rgba8Unorm,
            TextureFormat::Rgba8UnormSrgb => PyTextureFormat::Rgba8UnormSrgb,
            TextureFormat::Rgba8Snorm => PyTextureFormat::Rgba8Snorm,
            TextureFormat::Rgba8Uint => PyTextureFormat::Rgba8Uint,
            TextureFormat::Rgba8Sint => PyTextureFormat::Rgba8Sint,
            TextureFormat::Bgra8Unorm => PyTextureFormat::Bgra8Unorm,
            TextureFormat::Bgra8UnormSrgb => PyTextureFormat::Bgra8UnormSrgb,
            TextureFormat::Rgb9e5Ufloat => PyTextureFormat::Rgb9e5Ufloat,
            TextureFormat::Rgb10a2Uint => PyTextureFormat::Rgb10a2Uint,
            TextureFormat::Rgb10a2Unorm => PyTextureFormat::Rgb10a2Unorm,
            TextureFormat::Rg11b10Ufloat => PyTextureFormat::Rg11b10Ufloat,
            TextureFormat::R64Uint => PyTextureFormat::R64Uint,
            TextureFormat::Rg32Uint => PyTextureFormat::Rg32Uint,
            TextureFormat::Rg32Sint => PyTextureFormat::Rg32Sint,
            TextureFormat::Rg32Float => PyTextureFormat::Rg32Float,
            TextureFormat::Rgba16Uint => PyTextureFormat::Rgba16Uint,
            TextureFormat::Rgba16Sint => PyTextureFormat::Rgba16Sint,
            TextureFormat::Rgba16Unorm => PyTextureFormat::Rgba16Unorm,
            TextureFormat::Rgba16Snorm => PyTextureFormat::Rgba16Snorm,
            TextureFormat::Rgba16Float => PyTextureFormat::Rgba16Float,
            TextureFormat::Rgba32Uint => PyTextureFormat::Rgba32Uint,
            TextureFormat::Rgba32Sint => PyTextureFormat::Rgba32Sint,
            TextureFormat::Rgba32Float => PyTextureFormat::Rgba32Float,
            TextureFormat::Stencil8 => PyTextureFormat::Stencil8,
            TextureFormat::Depth16Unorm => PyTextureFormat::Depth16Unorm,
            TextureFormat::Depth24Plus => PyTextureFormat::Depth24Plus,
            TextureFormat::Depth24PlusStencil8 => PyTextureFormat::Depth24PlusStencil8,
            TextureFormat::Depth32Float => PyTextureFormat::Depth32Float,
            TextureFormat::Depth32FloatStencil8 => PyTextureFormat::Depth32FloatStencil8,
            TextureFormat::NV12 => PyTextureFormat::NV12,
            TextureFormat::P010 => PyTextureFormat::P010,
            TextureFormat::Bc1RgbaUnorm => PyTextureFormat::Bc1RgbaUnorm,
            TextureFormat::Bc1RgbaUnormSrgb => PyTextureFormat::Bc1RgbaUnormSrgb,
            TextureFormat::Bc2RgbaUnorm => PyTextureFormat::Bc2RgbaUnorm,
            TextureFormat::Bc2RgbaUnormSrgb => PyTextureFormat::Bc2RgbaUnormSrgb,
            TextureFormat::Bc3RgbaUnorm => PyTextureFormat::Bc3RgbaUnorm,
            TextureFormat::Bc3RgbaUnormSrgb => PyTextureFormat::Bc3RgbaUnormSrgb,
            TextureFormat::Bc4RUnorm => PyTextureFormat::Bc4RUnorm,
            TextureFormat::Bc4RSnorm => PyTextureFormat::Bc4RSnorm,
            TextureFormat::Bc5RgUnorm => PyTextureFormat::Bc5RgUnorm,
            TextureFormat::Bc5RgSnorm => PyTextureFormat::Bc5RgSnorm,
            TextureFormat::Bc6hRgbUfloat => PyTextureFormat::Bc6hRgbUfloat,
            TextureFormat::Bc6hRgbFloat => PyTextureFormat::Bc6hRgbFloat,
            TextureFormat::Bc7RgbaUnorm => PyTextureFormat::Bc7RgbaUnorm,
            TextureFormat::Bc7RgbaUnormSrgb => PyTextureFormat::Bc7RgbaUnormSrgb,
            TextureFormat::Etc2Rgb8Unorm => PyTextureFormat::Etc2Rgb8Unorm,
            TextureFormat::Etc2Rgb8UnormSrgb => PyTextureFormat::Etc2Rgb8UnormSrgb,
            TextureFormat::Etc2Rgb8A1Unorm => PyTextureFormat::Etc2Rgb8A1Unorm,
            TextureFormat::Etc2Rgb8A1UnormSrgb => PyTextureFormat::Etc2Rgb8A1UnormSrgb,
            TextureFormat::Etc2Rgba8Unorm => PyTextureFormat::Etc2Rgba8Unorm,
            TextureFormat::Etc2Rgba8UnormSrgb => PyTextureFormat::Etc2Rgba8UnormSrgb,
            TextureFormat::EacR11Unorm => PyTextureFormat::EacR11Unorm,
            TextureFormat::EacR11Snorm => PyTextureFormat::EacR11Snorm,
            TextureFormat::EacRg11Unorm => PyTextureFormat::EacRg11Unorm,
            TextureFormat::EacRg11Snorm => PyTextureFormat::EacRg11Snorm,
            TextureFormat::Astc { block, channel } => {
                return Err(PyValueError::new_err(unsupported_texture_format(
                    format_args!("Astc {{ block: {block:?}, channel: {channel:?} }}"),
                )));
            }
        })
    }
}
