[package]
name = "pybevy_world_serialization"
version = "0.3.0"
edition = "2024"
description = "World serialization components and assets for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }

[dependencies.bevy]
workspace = true
features = ["bevy_world_serialization", "bevy_asset", "bevy_log"]

[dev-dependencies]
ron = "0.12"
serde = "1.0"

[lints]
workspace = true
