[package]
name = "pybevy_shader"
version = "0.3.0"
edition = "2024"
description = "Shader type wrappers for PyBevy (Shader, ShaderRef, ShaderImport, etc.)"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
bevy = { workspace = true, features = ["bevy_render"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
naga = "29"

[lints]
workspace = true
