pub mod capsule3d;
pub mod cone;
pub mod cuboid;
pub mod cylinder;
pub mod plane3d;
pub mod sphere;
pub mod tetrahedron;
pub mod torus;
pub mod triangle3d;

pub use capsule3d::PyCapsule3d;
pub use cone::PyCone;
pub use cuboid::PyCuboid;
pub use cylinder::PyCylinder;
pub use plane3d::PyPlane3d;
pub use sphere::PySphere;
pub use tetrahedron::PyTetrahedron;
pub use torus::PyTorus;
pub use triangle3d::PyTriangle3d;
