[package]
name = "pybevy_image"
version = "0.2.1"
edition = "2024"
description = "Image asset for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_math = { workspace = true }
pybevy_color = { workspace = true }
pybevy_wgpu = { workspace = true }
pybevy_array = { workspace = true, features = ["pyo3"] }
image = { version = "0.25.6", default-features = false, features = ["jpeg", "png", "bmp", "dds", "exr", "hdr", "qoi", "pnm", "tga", "tiff", "webp"] }

[dependencies.bevy]
workspace = true
features = ["bevy_image", "bevy_render", "png", "jpeg", "bmp", "dds", "hdr", "ktx2", "qoi", "pnm", "tga", "tiff", "webp", "exr", "ff", "gif", "ico"]

[lints]
workspace = true
