[package]
name = "pybevy_text"
version = "0.2.1"
edition = "2024"
description = "Text types for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true }
bevy = { workspace = true, features = ["bevy_text", "bevy_sprite"] }
pybevy_macros = { workspace = true }
pybevy_core = { workspace = true }
pybevy_color = { workspace = true }
pybevy_image = { workspace = true }
pybevy_math = { workspace = true }
numpy = { workspace = true }

[lints]
workspace = true
