[package]
name = "pybevy_camera"
version = "0.2.1"
edition = "2024"
description = "Camera components for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
numpy = { workspace = true }
pyo3 = { workspace = true, features = ["macros"] }
pybevy_color = { workspace = true }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_math = { workspace = true }
pybevy_render = { workspace = true }
pybevy_sprite = { workspace = true }
pybevy_transform = { workspace = true }
pybevy_window = { workspace = true }

[dependencies.bevy]
workspace = true
features = [
    "bevy_render",
    "bevy_core_pipeline",
    "bevy_image",
    "bevy_camera",
]

