[package]
name = "pybevy_bytecodevm"
version = "0.2.1"
edition = "2024"
description = "Bytecode VM for PyBevy expressions"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3.workspace = true
bevy_ecs = "0.18"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "vm_pool"
harness = false
