use bevy::input::keyboard::Key;
use pybevy_macros::pyenum;
use pyo3::{exceptions::PyValueError, prelude::*};

use crate::native_key::PyNativeKey;

#[pyenum(Key, manual, empty_tuple)]
#[pyclass(
    name = "Key",
    module = "pybevy.input",
    eq,
    frozen,
    from_py_object,
    hash
)]
#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum PyKey {
    Character { value: String },
    Unidentified { value: PyNativeKey },
    Dead { value: Option<char> },
    Alt(),
    AltGraph(),
    CapsLock(),
    Control(),
    Fn(),
    FnLock(),
    NumLock(),
    ScrollLock(),
    Shift(),
    Symbol(),
    SymbolLock(),
    Meta(),
    Hyper(),
    Super(),
    Enter(),
    Tab(),
    Space(),
    ArrowDown(),
    ArrowLeft(),
    ArrowRight(),
    ArrowUp(),
    End(),
    Home(),
    PageDown(),
    PageUp(),
    Backspace(),
    Clear(),
    Copy(),
    CrSel(),
    Cut(),
    Delete(),
    EraseEof(),
    ExSel(),
    Insert(),
    Paste(),
    Redo(),
    Undo(),
    Accept(),
    Again(),
    Attn(),
    Cancel(),
    ContextMenu(),
    Escape(),
    Execute(),
    Find(),
    Help(),
    Pause(),
    Play(),
    Props(),
    Select(),
    ZoomIn(),
    ZoomOut(),
    BrightnessDown(),
    BrightnessUp(),
    Eject(),
    LogOff(),
    Power(),
    PowerOff(),
    PrintScreen(),
    Hibernate(),
    Standby(),
    WakeUp(),
    AllCandidates(),
    Alphanumeric(),
    CodeInput(),
    Compose(),
    Convert(),
    FinalMode(),
    GroupFirst(),
    GroupLast(),
    GroupNext(),
    GroupPrevious(),
    ModeChange(),
    NextCandidate(),
    NonConvert(),
    PreviousCandidate(),
    Process(),
    SingleCandidate(),
    HangulMode(),
    HanjaMode(),
    JunjaMode(),
    Eisu(),
    Hankaku(),
    Hiragana(),
    HiraganaKatakana(),
    KanaMode(),
    KanjiMode(),
    Katakana(),
    Romaji(),
    Zenkaku(),
    ZenkakuHankaku(),
    Soft1(),
    Soft2(),
    Soft3(),
    Soft4(),
    ChannelDown(),
    ChannelUp(),
    Close(),
    MailForward(),
    MailReply(),
    MailSend(),
    MediaClose(),
    MediaFastForward(),
    MediaPause(),
    MediaPlay(),
    MediaPlayPause(),
    MediaRecord(),
    MediaRewind(),
    MediaStop(),
    MediaTrackNext(),
    MediaTrackPrevious(),
    New(),
    Open(),
    Print(),
    Save(),
    SpellCheck(),
    Key11(),
    Key12(),
    AudioBalanceLeft(),
    AudioBalanceRight(),
    AudioBassBoostDown(),
    AudioBassBoostToggle(),
    AudioBassBoostUp(),
    AudioFaderFront(),
    AudioFaderRear(),
    AudioSurroundModeNext(),
    AudioTrebleDown(),
    AudioTrebleUp(),
    AudioVolumeDown(),
    AudioVolumeUp(),
    AudioVolumeMute(),
    MicrophoneToggle(),
    MicrophoneVolumeDown(),
    MicrophoneVolumeUp(),
    MicrophoneVolumeMute(),
    SpeechCorrectionList(),
    SpeechInputToggle(),
    LaunchApplication1(),
    LaunchApplication2(),
    LaunchCalendar(),
    LaunchContacts(),
    LaunchMail(),
    LaunchMediaPlayer(),
    LaunchMusicPlayer(),
    LaunchPhone(),
    LaunchScreenSaver(),
    LaunchSpreadsheet(),
    LaunchWebBrowser(),
    LaunchWebCam(),
    LaunchWordProcessor(),
    BrowserBack(),
    BrowserFavorites(),
    BrowserForward(),
    BrowserHome(),
    BrowserRefresh(),
    BrowserSearch(),
    BrowserStop(),
    AppSwitch(),
    Call(),
    Camera(),
    CameraFocus(),
    EndCall(),
    GoBack(),
    GoHome(),
    HeadsetHook(),
    LastNumberRedial(),
    Notification(),
    MannerMode(),
    VoiceDial(),
    TV(),
    TV3DMode(),
    TVAntennaCable(),
    TVAudioDescription(),
    TVAudioDescriptionMixDown(),
    TVAudioDescriptionMixUp(),
    TVContentsMenu(),
    TVDataService(),
    TVInput(),
    TVInputComponent1(),
    TVInputComponent2(),
    TVInputComposite1(),
    TVInputComposite2(),
    TVInputHDMI1(),
    TVInputHDMI2(),
    TVInputHDMI3(),
    TVInputHDMI4(),
    TVInputVGA1(),
    TVMediaContext(),
    TVNetwork(),
    TVNumberEntry(),
    TVPower(),
    TVRadioService(),
    TVSatellite(),
    TVSatelliteBS(),
    TVSatelliteCS(),
    TVSatelliteToggle(),
    TVTerrestrialAnalog(),
    TVTerrestrialDigital(),
    TVTimer(),
    AVRInput(),
    AVRPower(),
    ColorF0Red(),
    ColorF1Green(),
    ColorF2Yellow(),
    ColorF3Blue(),
    ColorF4Grey(),
    ColorF5Brown(),
    ClosedCaptionToggle(),
    Dimmer(),
    DisplaySwap(),
    DVR(),
    Exit(),
    FavoriteClear0(),
    FavoriteClear1(),
    FavoriteClear2(),
    FavoriteClear3(),
    FavoriteRecall0(),
    FavoriteRecall1(),
    FavoriteRecall2(),
    FavoriteRecall3(),
    FavoriteStore0(),
    FavoriteStore1(),
    FavoriteStore2(),
    FavoriteStore3(),
    Guide(),
    GuideNextDay(),
    GuidePreviousDay(),
    Info(),
    InstantReplay(),
    Link(),
    ListProgram(),
    LiveContent(),
    Lock(),
    MediaApps(),
    MediaAudioTrack(),
    MediaLast(),
    MediaSkipBackward(),
    MediaSkipForward(),
    MediaStepBackward(),
    MediaStepForward(),
    MediaTopMenu(),
    NavigateIn(),
    NavigateNext(),
    NavigateOut(),
    NavigatePrevious(),
    NextFavoriteChannel(),
    NextUserProfile(),
    OnDemand(),
    Pairing(),
    PinPDown(),
    PinPMove(),
    PinPToggle(),
    PinPUp(),
    PlaySpeedDown(),
    PlaySpeedReset(),
    PlaySpeedUp(),
    RandomToggle(),
    RcLowBattery(),
    RecordSpeedNext(),
    RfBypass(),
    ScanChannelsToggle(),
    ScreenModeNext(),
    Settings(),
    SplitScreenToggle(),
    STBInput(),
    STBPower(),
    Subtitle(),
    Teletext(),
    VideoModeNext(),
    Wink(),
    ZoomToggle(),
    F1(),
    F2(),
    F3(),
    F4(),
    F5(),
    F6(),
    F7(),
    F8(),
    F9(),
    F10(),
    F11(),
    F12(),
    F13(),
    F14(),
    F15(),
    F16(),
    F17(),
    F18(),
    F19(),
    F20(),
    F21(),
    F22(),
    F23(),
    F24(),
    F25(),
    F26(),
    F27(),
    F28(),
    F29(),
    F30(),
    F31(),
    F32(),
    F33(),
    F34(),
    F35(),
}

impl TryFrom<&Key> for PyKey {
    type Error = PyErr;

    fn try_from(value: &Key) -> PyResult<Self> {
        match value {
            Key::Character(value) => Ok(Self::Character {
                value: value.to_string(),
            }),
            Key::Unidentified(value) => Ok(Self::Unidentified {
                value: value.into(),
            }),
            Key::Dead(value) => Ok(Self::Dead { value: *value }),
            Key::Alt => Ok(Self::Alt()),
            Key::AltGraph => Ok(Self::AltGraph()),
            Key::CapsLock => Ok(Self::CapsLock()),
            Key::Control => Ok(Self::Control()),
            Key::Fn => Ok(Self::Fn()),
            Key::FnLock => Ok(Self::FnLock()),
            Key::NumLock => Ok(Self::NumLock()),
            Key::ScrollLock => Ok(Self::ScrollLock()),
            Key::Shift => Ok(Self::Shift()),
            Key::Symbol => Ok(Self::Symbol()),
            Key::SymbolLock => Ok(Self::SymbolLock()),
            Key::Meta => Ok(Self::Meta()),
            Key::Hyper => Ok(Self::Hyper()),
            Key::Super => Ok(Self::Super()),
            Key::Enter => Ok(Self::Enter()),
            Key::Tab => Ok(Self::Tab()),
            Key::Space => Ok(Self::Space()),
            Key::ArrowDown => Ok(Self::ArrowDown()),
            Key::ArrowLeft => Ok(Self::ArrowLeft()),
            Key::ArrowRight => Ok(Self::ArrowRight()),
            Key::ArrowUp => Ok(Self::ArrowUp()),
            Key::End => Ok(Self::End()),
            Key::Home => Ok(Self::Home()),
            Key::PageDown => Ok(Self::PageDown()),
            Key::PageUp => Ok(Self::PageUp()),
            Key::Backspace => Ok(Self::Backspace()),
            Key::Clear => Ok(Self::Clear()),
            Key::Copy => Ok(Self::Copy()),
            Key::CrSel => Ok(Self::CrSel()),
            Key::Cut => Ok(Self::Cut()),
            Key::Delete => Ok(Self::Delete()),
            Key::EraseEof => Ok(Self::EraseEof()),
            Key::ExSel => Ok(Self::ExSel()),
            Key::Insert => Ok(Self::Insert()),
            Key::Paste => Ok(Self::Paste()),
            Key::Redo => Ok(Self::Redo()),
            Key::Undo => Ok(Self::Undo()),
            Key::Accept => Ok(Self::Accept()),
            Key::Again => Ok(Self::Again()),
            Key::Attn => Ok(Self::Attn()),
            Key::Cancel => Ok(Self::Cancel()),
            Key::ContextMenu => Ok(Self::ContextMenu()),
            Key::Escape => Ok(Self::Escape()),
            Key::Execute => Ok(Self::Execute()),
            Key::Find => Ok(Self::Find()),
            Key::Help => Ok(Self::Help()),
            Key::Pause => Ok(Self::Pause()),
            Key::Play => Ok(Self::Play()),
            Key::Props => Ok(Self::Props()),
            Key::Select => Ok(Self::Select()),
            Key::ZoomIn => Ok(Self::ZoomIn()),
            Key::ZoomOut => Ok(Self::ZoomOut()),
            Key::BrightnessDown => Ok(Self::BrightnessDown()),
            Key::BrightnessUp => Ok(Self::BrightnessUp()),
            Key::Eject => Ok(Self::Eject()),
            Key::LogOff => Ok(Self::LogOff()),
            Key::Power => Ok(Self::Power()),
            Key::PowerOff => Ok(Self::PowerOff()),
            Key::PrintScreen => Ok(Self::PrintScreen()),
            Key::Hibernate => Ok(Self::Hibernate()),
            Key::Standby => Ok(Self::Standby()),
            Key::WakeUp => Ok(Self::WakeUp()),
            Key::AllCandidates => Ok(Self::AllCandidates()),
            Key::Alphanumeric => Ok(Self::Alphanumeric()),
            Key::CodeInput => Ok(Self::CodeInput()),
            Key::Compose => Ok(Self::Compose()),
            Key::Convert => Ok(Self::Convert()),
            Key::FinalMode => Ok(Self::FinalMode()),
            Key::GroupFirst => Ok(Self::GroupFirst()),
            Key::GroupLast => Ok(Self::GroupLast()),
            Key::GroupNext => Ok(Self::GroupNext()),
            Key::GroupPrevious => Ok(Self::GroupPrevious()),
            Key::ModeChange => Ok(Self::ModeChange()),
            Key::NextCandidate => Ok(Self::NextCandidate()),
            Key::NonConvert => Ok(Self::NonConvert()),
            Key::PreviousCandidate => Ok(Self::PreviousCandidate()),
            Key::Process => Ok(Self::Process()),
            Key::SingleCandidate => Ok(Self::SingleCandidate()),
            Key::HangulMode => Ok(Self::HangulMode()),
            Key::HanjaMode => Ok(Self::HanjaMode()),
            Key::JunjaMode => Ok(Self::JunjaMode()),
            Key::Eisu => Ok(Self::Eisu()),
            Key::Hankaku => Ok(Self::Hankaku()),
            Key::Hiragana => Ok(Self::Hiragana()),
            Key::HiraganaKatakana => Ok(Self::HiraganaKatakana()),
            Key::KanaMode => Ok(Self::KanaMode()),
            Key::KanjiMode => Ok(Self::KanjiMode()),
            Key::Katakana => Ok(Self::Katakana()),
            Key::Romaji => Ok(Self::Romaji()),
            Key::Zenkaku => Ok(Self::Zenkaku()),
            Key::ZenkakuHankaku => Ok(Self::ZenkakuHankaku()),
            Key::Soft1 => Ok(Self::Soft1()),
            Key::Soft2 => Ok(Self::Soft2()),
            Key::Soft3 => Ok(Self::Soft3()),
            Key::Soft4 => Ok(Self::Soft4()),
            Key::ChannelDown => Ok(Self::ChannelDown()),
            Key::ChannelUp => Ok(Self::ChannelUp()),
            Key::Close => Ok(Self::Close()),
            Key::MailForward => Ok(Self::MailForward()),
            Key::MailReply => Ok(Self::MailReply()),
            Key::MailSend => Ok(Self::MailSend()),
            Key::MediaClose => Ok(Self::MediaClose()),
            Key::MediaFastForward => Ok(Self::MediaFastForward()),
            Key::MediaPause => Ok(Self::MediaPause()),
            Key::MediaPlay => Ok(Self::MediaPlay()),
            Key::MediaPlayPause => Ok(Self::MediaPlayPause()),
            Key::MediaRecord => Ok(Self::MediaRecord()),
            Key::MediaRewind => Ok(Self::MediaRewind()),
            Key::MediaStop => Ok(Self::MediaStop()),
            Key::MediaTrackNext => Ok(Self::MediaTrackNext()),
            Key::MediaTrackPrevious => Ok(Self::MediaTrackPrevious()),
            Key::New => Ok(Self::New()),
            Key::Open => Ok(Self::Open()),
            Key::Print => Ok(Self::Print()),
            Key::Save => Ok(Self::Save()),
            Key::SpellCheck => Ok(Self::SpellCheck()),
            Key::Key11 => Ok(Self::Key11()),
            Key::Key12 => Ok(Self::Key12()),
            Key::AudioBalanceLeft => Ok(Self::AudioBalanceLeft()),
            Key::AudioBalanceRight => Ok(Self::AudioBalanceRight()),
            Key::AudioBassBoostDown => Ok(Self::AudioBassBoostDown()),
            Key::AudioBassBoostToggle => Ok(Self::AudioBassBoostToggle()),
            Key::AudioBassBoostUp => Ok(Self::AudioBassBoostUp()),
            Key::AudioFaderFront => Ok(Self::AudioFaderFront()),
            Key::AudioFaderRear => Ok(Self::AudioFaderRear()),
            Key::AudioSurroundModeNext => Ok(Self::AudioSurroundModeNext()),
            Key::AudioTrebleDown => Ok(Self::AudioTrebleDown()),
            Key::AudioTrebleUp => Ok(Self::AudioTrebleUp()),
            Key::AudioVolumeDown => Ok(Self::AudioVolumeDown()),
            Key::AudioVolumeUp => Ok(Self::AudioVolumeUp()),
            Key::AudioVolumeMute => Ok(Self::AudioVolumeMute()),
            Key::MicrophoneToggle => Ok(Self::MicrophoneToggle()),
            Key::MicrophoneVolumeDown => Ok(Self::MicrophoneVolumeDown()),
            Key::MicrophoneVolumeUp => Ok(Self::MicrophoneVolumeUp()),
            Key::MicrophoneVolumeMute => Ok(Self::MicrophoneVolumeMute()),
            Key::SpeechCorrectionList => Ok(Self::SpeechCorrectionList()),
            Key::SpeechInputToggle => Ok(Self::SpeechInputToggle()),
            Key::LaunchApplication1 => Ok(Self::LaunchApplication1()),
            Key::LaunchApplication2 => Ok(Self::LaunchApplication2()),
            Key::LaunchCalendar => Ok(Self::LaunchCalendar()),
            Key::LaunchContacts => Ok(Self::LaunchContacts()),
            Key::LaunchMail => Ok(Self::LaunchMail()),
            Key::LaunchMediaPlayer => Ok(Self::LaunchMediaPlayer()),
            Key::LaunchMusicPlayer => Ok(Self::LaunchMusicPlayer()),
            Key::LaunchPhone => Ok(Self::LaunchPhone()),
            Key::LaunchScreenSaver => Ok(Self::LaunchScreenSaver()),
            Key::LaunchSpreadsheet => Ok(Self::LaunchSpreadsheet()),
            Key::LaunchWebBrowser => Ok(Self::LaunchWebBrowser()),
            Key::LaunchWebCam => Ok(Self::LaunchWebCam()),
            Key::LaunchWordProcessor => Ok(Self::LaunchWordProcessor()),
            Key::BrowserBack => Ok(Self::BrowserBack()),
            Key::BrowserFavorites => Ok(Self::BrowserFavorites()),
            Key::BrowserForward => Ok(Self::BrowserForward()),
            Key::BrowserHome => Ok(Self::BrowserHome()),
            Key::BrowserRefresh => Ok(Self::BrowserRefresh()),
            Key::BrowserSearch => Ok(Self::BrowserSearch()),
            Key::BrowserStop => Ok(Self::BrowserStop()),
            Key::AppSwitch => Ok(Self::AppSwitch()),
            Key::Call => Ok(Self::Call()),
            Key::Camera => Ok(Self::Camera()),
            Key::CameraFocus => Ok(Self::CameraFocus()),
            Key::EndCall => Ok(Self::EndCall()),
            Key::GoBack => Ok(Self::GoBack()),
            Key::GoHome => Ok(Self::GoHome()),
            Key::HeadsetHook => Ok(Self::HeadsetHook()),
            Key::LastNumberRedial => Ok(Self::LastNumberRedial()),
            Key::Notification => Ok(Self::Notification()),
            Key::MannerMode => Ok(Self::MannerMode()),
            Key::VoiceDial => Ok(Self::VoiceDial()),
            Key::TV => Ok(Self::TV()),
            Key::TV3DMode => Ok(Self::TV3DMode()),
            Key::TVAntennaCable => Ok(Self::TVAntennaCable()),
            Key::TVAudioDescription => Ok(Self::TVAudioDescription()),
            Key::TVAudioDescriptionMixDown => Ok(Self::TVAudioDescriptionMixDown()),
            Key::TVAudioDescriptionMixUp => Ok(Self::TVAudioDescriptionMixUp()),
            Key::TVContentsMenu => Ok(Self::TVContentsMenu()),
            Key::TVDataService => Ok(Self::TVDataService()),
            Key::TVInput => Ok(Self::TVInput()),
            Key::TVInputComponent1 => Ok(Self::TVInputComponent1()),
            Key::TVInputComponent2 => Ok(Self::TVInputComponent2()),
            Key::TVInputComposite1 => Ok(Self::TVInputComposite1()),
            Key::TVInputComposite2 => Ok(Self::TVInputComposite2()),
            Key::TVInputHDMI1 => Ok(Self::TVInputHDMI1()),
            Key::TVInputHDMI2 => Ok(Self::TVInputHDMI2()),
            Key::TVInputHDMI3 => Ok(Self::TVInputHDMI3()),
            Key::TVInputHDMI4 => Ok(Self::TVInputHDMI4()),
            Key::TVInputVGA1 => Ok(Self::TVInputVGA1()),
            Key::TVMediaContext => Ok(Self::TVMediaContext()),
            Key::TVNetwork => Ok(Self::TVNetwork()),
            Key::TVNumberEntry => Ok(Self::TVNumberEntry()),
            Key::TVPower => Ok(Self::TVPower()),
            Key::TVRadioService => Ok(Self::TVRadioService()),
            Key::TVSatellite => Ok(Self::TVSatellite()),
            Key::TVSatelliteBS => Ok(Self::TVSatelliteBS()),
            Key::TVSatelliteCS => Ok(Self::TVSatelliteCS()),
            Key::TVSatelliteToggle => Ok(Self::TVSatelliteToggle()),
            Key::TVTerrestrialAnalog => Ok(Self::TVTerrestrialAnalog()),
            Key::TVTerrestrialDigital => Ok(Self::TVTerrestrialDigital()),
            Key::TVTimer => Ok(Self::TVTimer()),
            Key::AVRInput => Ok(Self::AVRInput()),
            Key::AVRPower => Ok(Self::AVRPower()),
            Key::ColorF0Red => Ok(Self::ColorF0Red()),
            Key::ColorF1Green => Ok(Self::ColorF1Green()),
            Key::ColorF2Yellow => Ok(Self::ColorF2Yellow()),
            Key::ColorF3Blue => Ok(Self::ColorF3Blue()),
            Key::ColorF4Grey => Ok(Self::ColorF4Grey()),
            Key::ColorF5Brown => Ok(Self::ColorF5Brown()),
            Key::ClosedCaptionToggle => Ok(Self::ClosedCaptionToggle()),
            Key::Dimmer => Ok(Self::Dimmer()),
            Key::DisplaySwap => Ok(Self::DisplaySwap()),
            Key::DVR => Ok(Self::DVR()),
            Key::Exit => Ok(Self::Exit()),
            Key::FavoriteClear0 => Ok(Self::FavoriteClear0()),
            Key::FavoriteClear1 => Ok(Self::FavoriteClear1()),
            Key::FavoriteClear2 => Ok(Self::FavoriteClear2()),
            Key::FavoriteClear3 => Ok(Self::FavoriteClear3()),
            Key::FavoriteRecall0 => Ok(Self::FavoriteRecall0()),
            Key::FavoriteRecall1 => Ok(Self::FavoriteRecall1()),
            Key::FavoriteRecall2 => Ok(Self::FavoriteRecall2()),
            Key::FavoriteRecall3 => Ok(Self::FavoriteRecall3()),
            Key::FavoriteStore0 => Ok(Self::FavoriteStore0()),
            Key::FavoriteStore1 => Ok(Self::FavoriteStore1()),
            Key::FavoriteStore2 => Ok(Self::FavoriteStore2()),
            Key::FavoriteStore3 => Ok(Self::FavoriteStore3()),
            Key::Guide => Ok(Self::Guide()),
            Key::GuideNextDay => Ok(Self::GuideNextDay()),
            Key::GuidePreviousDay => Ok(Self::GuidePreviousDay()),
            Key::Info => Ok(Self::Info()),
            Key::InstantReplay => Ok(Self::InstantReplay()),
            Key::Link => Ok(Self::Link()),
            Key::ListProgram => Ok(Self::ListProgram()),
            Key::LiveContent => Ok(Self::LiveContent()),
            Key::Lock => Ok(Self::Lock()),
            Key::MediaApps => Ok(Self::MediaApps()),
            Key::MediaAudioTrack => Ok(Self::MediaAudioTrack()),
            Key::MediaLast => Ok(Self::MediaLast()),
            Key::MediaSkipBackward => Ok(Self::MediaSkipBackward()),
            Key::MediaSkipForward => Ok(Self::MediaSkipForward()),
            Key::MediaStepBackward => Ok(Self::MediaStepBackward()),
            Key::MediaStepForward => Ok(Self::MediaStepForward()),
            Key::MediaTopMenu => Ok(Self::MediaTopMenu()),
            Key::NavigateIn => Ok(Self::NavigateIn()),
            Key::NavigateNext => Ok(Self::NavigateNext()),
            Key::NavigateOut => Ok(Self::NavigateOut()),
            Key::NavigatePrevious => Ok(Self::NavigatePrevious()),
            Key::NextFavoriteChannel => Ok(Self::NextFavoriteChannel()),
            Key::NextUserProfile => Ok(Self::NextUserProfile()),
            Key::OnDemand => Ok(Self::OnDemand()),
            Key::Pairing => Ok(Self::Pairing()),
            Key::PinPDown => Ok(Self::PinPDown()),
            Key::PinPMove => Ok(Self::PinPMove()),
            Key::PinPToggle => Ok(Self::PinPToggle()),
            Key::PinPUp => Ok(Self::PinPUp()),
            Key::PlaySpeedDown => Ok(Self::PlaySpeedDown()),
            Key::PlaySpeedReset => Ok(Self::PlaySpeedReset()),
            Key::PlaySpeedUp => Ok(Self::PlaySpeedUp()),
            Key::RandomToggle => Ok(Self::RandomToggle()),
            Key::RcLowBattery => Ok(Self::RcLowBattery()),
            Key::RecordSpeedNext => Ok(Self::RecordSpeedNext()),
            Key::RfBypass => Ok(Self::RfBypass()),
            Key::ScanChannelsToggle => Ok(Self::ScanChannelsToggle()),
            Key::ScreenModeNext => Ok(Self::ScreenModeNext()),
            Key::Settings => Ok(Self::Settings()),
            Key::SplitScreenToggle => Ok(Self::SplitScreenToggle()),
            Key::STBInput => Ok(Self::STBInput()),
            Key::STBPower => Ok(Self::STBPower()),
            Key::Subtitle => Ok(Self::Subtitle()),
            Key::Teletext => Ok(Self::Teletext()),
            Key::VideoModeNext => Ok(Self::VideoModeNext()),
            Key::Wink => Ok(Self::Wink()),
            Key::ZoomToggle => Ok(Self::ZoomToggle()),
            Key::F1 => Ok(Self::F1()),
            Key::F2 => Ok(Self::F2()),
            Key::F3 => Ok(Self::F3()),
            Key::F4 => Ok(Self::F4()),
            Key::F5 => Ok(Self::F5()),
            Key::F6 => Ok(Self::F6()),
            Key::F7 => Ok(Self::F7()),
            Key::F8 => Ok(Self::F8()),
            Key::F9 => Ok(Self::F9()),
            Key::F10 => Ok(Self::F10()),
            Key::F11 => Ok(Self::F11()),
            Key::F12 => Ok(Self::F12()),
            Key::F13 => Ok(Self::F13()),
            Key::F14 => Ok(Self::F14()),
            Key::F15 => Ok(Self::F15()),
            Key::F16 => Ok(Self::F16()),
            Key::F17 => Ok(Self::F17()),
            Key::F18 => Ok(Self::F18()),
            Key::F19 => Ok(Self::F19()),
            Key::F20 => Ok(Self::F20()),
            Key::F21 => Ok(Self::F21()),
            Key::F22 => Ok(Self::F22()),
            Key::F23 => Ok(Self::F23()),
            Key::F24 => Ok(Self::F24()),
            Key::F25 => Ok(Self::F25()),
            Key::F26 => Ok(Self::F26()),
            Key::F27 => Ok(Self::F27()),
            Key::F28 => Ok(Self::F28()),
            Key::F29 => Ok(Self::F29()),
            Key::F30 => Ok(Self::F30()),
            Key::F31 => Ok(Self::F31()),
            Key::F32 => Ok(Self::F32()),
            Key::F33 => Ok(Self::F33()),
            Key::F34 => Ok(Self::F34()),
            Key::F35 => Ok(Self::F35()),
            _ => Err(PyValueError::new_err("unsupported logical key variant")),
        }
    }
}

impl From<PyKey> for Key {
    fn from(value: PyKey) -> Self {
        match value {
            PyKey::Character { value } => Key::Character(value.into()),
            PyKey::Unidentified { value } => Key::Unidentified(value.into()),
            PyKey::Dead { value } => Key::Dead(value),
            PyKey::Alt() => Key::Alt,
            PyKey::AltGraph() => Key::AltGraph,
            PyKey::CapsLock() => Key::CapsLock,
            PyKey::Control() => Key::Control,
            PyKey::Fn() => Key::Fn,
            PyKey::FnLock() => Key::FnLock,
            PyKey::NumLock() => Key::NumLock,
            PyKey::ScrollLock() => Key::ScrollLock,
            PyKey::Shift() => Key::Shift,
            PyKey::Symbol() => Key::Symbol,
            PyKey::SymbolLock() => Key::SymbolLock,
            PyKey::Meta() => Key::Meta,
            PyKey::Hyper() => Key::Hyper,
            PyKey::Super() => Key::Super,
            PyKey::Enter() => Key::Enter,
            PyKey::Tab() => Key::Tab,
            PyKey::Space() => Key::Space,
            PyKey::ArrowDown() => Key::ArrowDown,
            PyKey::ArrowLeft() => Key::ArrowLeft,
            PyKey::ArrowRight() => Key::ArrowRight,
            PyKey::ArrowUp() => Key::ArrowUp,
            PyKey::End() => Key::End,
            PyKey::Home() => Key::Home,
            PyKey::PageDown() => Key::PageDown,
            PyKey::PageUp() => Key::PageUp,
            PyKey::Backspace() => Key::Backspace,
            PyKey::Clear() => Key::Clear,
            PyKey::Copy() => Key::Copy,
            PyKey::CrSel() => Key::CrSel,
            PyKey::Cut() => Key::Cut,
            PyKey::Delete() => Key::Delete,
            PyKey::EraseEof() => Key::EraseEof,
            PyKey::ExSel() => Key::ExSel,
            PyKey::Insert() => Key::Insert,
            PyKey::Paste() => Key::Paste,
            PyKey::Redo() => Key::Redo,
            PyKey::Undo() => Key::Undo,
            PyKey::Accept() => Key::Accept,
            PyKey::Again() => Key::Again,
            PyKey::Attn() => Key::Attn,
            PyKey::Cancel() => Key::Cancel,
            PyKey::ContextMenu() => Key::ContextMenu,
            PyKey::Escape() => Key::Escape,
            PyKey::Execute() => Key::Execute,
            PyKey::Find() => Key::Find,
            PyKey::Help() => Key::Help,
            PyKey::Pause() => Key::Pause,
            PyKey::Play() => Key::Play,
            PyKey::Props() => Key::Props,
            PyKey::Select() => Key::Select,
            PyKey::ZoomIn() => Key::ZoomIn,
            PyKey::ZoomOut() => Key::ZoomOut,
            PyKey::BrightnessDown() => Key::BrightnessDown,
            PyKey::BrightnessUp() => Key::BrightnessUp,
            PyKey::Eject() => Key::Eject,
            PyKey::LogOff() => Key::LogOff,
            PyKey::Power() => Key::Power,
            PyKey::PowerOff() => Key::PowerOff,
            PyKey::PrintScreen() => Key::PrintScreen,
            PyKey::Hibernate() => Key::Hibernate,
            PyKey::Standby() => Key::Standby,
            PyKey::WakeUp() => Key::WakeUp,
            PyKey::AllCandidates() => Key::AllCandidates,
            PyKey::Alphanumeric() => Key::Alphanumeric,
            PyKey::CodeInput() => Key::CodeInput,
            PyKey::Compose() => Key::Compose,
            PyKey::Convert() => Key::Convert,
            PyKey::FinalMode() => Key::FinalMode,
            PyKey::GroupFirst() => Key::GroupFirst,
            PyKey::GroupLast() => Key::GroupLast,
            PyKey::GroupNext() => Key::GroupNext,
            PyKey::GroupPrevious() => Key::GroupPrevious,
            PyKey::ModeChange() => Key::ModeChange,
            PyKey::NextCandidate() => Key::NextCandidate,
            PyKey::NonConvert() => Key::NonConvert,
            PyKey::PreviousCandidate() => Key::PreviousCandidate,
            PyKey::Process() => Key::Process,
            PyKey::SingleCandidate() => Key::SingleCandidate,
            PyKey::HangulMode() => Key::HangulMode,
            PyKey::HanjaMode() => Key::HanjaMode,
            PyKey::JunjaMode() => Key::JunjaMode,
            PyKey::Eisu() => Key::Eisu,
            PyKey::Hankaku() => Key::Hankaku,
            PyKey::Hiragana() => Key::Hiragana,
            PyKey::HiraganaKatakana() => Key::HiraganaKatakana,
            PyKey::KanaMode() => Key::KanaMode,
            PyKey::KanjiMode() => Key::KanjiMode,
            PyKey::Katakana() => Key::Katakana,
            PyKey::Romaji() => Key::Romaji,
            PyKey::Zenkaku() => Key::Zenkaku,
            PyKey::ZenkakuHankaku() => Key::ZenkakuHankaku,
            PyKey::Soft1() => Key::Soft1,
            PyKey::Soft2() => Key::Soft2,
            PyKey::Soft3() => Key::Soft3,
            PyKey::Soft4() => Key::Soft4,
            PyKey::ChannelDown() => Key::ChannelDown,
            PyKey::ChannelUp() => Key::ChannelUp,
            PyKey::Close() => Key::Close,
            PyKey::MailForward() => Key::MailForward,
            PyKey::MailReply() => Key::MailReply,
            PyKey::MailSend() => Key::MailSend,
            PyKey::MediaClose() => Key::MediaClose,
            PyKey::MediaFastForward() => Key::MediaFastForward,
            PyKey::MediaPause() => Key::MediaPause,
            PyKey::MediaPlay() => Key::MediaPlay,
            PyKey::MediaPlayPause() => Key::MediaPlayPause,
            PyKey::MediaRecord() => Key::MediaRecord,
            PyKey::MediaRewind() => Key::MediaRewind,
            PyKey::MediaStop() => Key::MediaStop,
            PyKey::MediaTrackNext() => Key::MediaTrackNext,
            PyKey::MediaTrackPrevious() => Key::MediaTrackPrevious,
            PyKey::New() => Key::New,
            PyKey::Open() => Key::Open,
            PyKey::Print() => Key::Print,
            PyKey::Save() => Key::Save,
            PyKey::SpellCheck() => Key::SpellCheck,
            PyKey::Key11() => Key::Key11,
            PyKey::Key12() => Key::Key12,
            PyKey::AudioBalanceLeft() => Key::AudioBalanceLeft,
            PyKey::AudioBalanceRight() => Key::AudioBalanceRight,
            PyKey::AudioBassBoostDown() => Key::AudioBassBoostDown,
            PyKey::AudioBassBoostToggle() => Key::AudioBassBoostToggle,
            PyKey::AudioBassBoostUp() => Key::AudioBassBoostUp,
            PyKey::AudioFaderFront() => Key::AudioFaderFront,
            PyKey::AudioFaderRear() => Key::AudioFaderRear,
            PyKey::AudioSurroundModeNext() => Key::AudioSurroundModeNext,
            PyKey::AudioTrebleDown() => Key::AudioTrebleDown,
            PyKey::AudioTrebleUp() => Key::AudioTrebleUp,
            PyKey::AudioVolumeDown() => Key::AudioVolumeDown,
            PyKey::AudioVolumeUp() => Key::AudioVolumeUp,
            PyKey::AudioVolumeMute() => Key::AudioVolumeMute,
            PyKey::MicrophoneToggle() => Key::MicrophoneToggle,
            PyKey::MicrophoneVolumeDown() => Key::MicrophoneVolumeDown,
            PyKey::MicrophoneVolumeUp() => Key::MicrophoneVolumeUp,
            PyKey::MicrophoneVolumeMute() => Key::MicrophoneVolumeMute,
            PyKey::SpeechCorrectionList() => Key::SpeechCorrectionList,
            PyKey::SpeechInputToggle() => Key::SpeechInputToggle,
            PyKey::LaunchApplication1() => Key::LaunchApplication1,
            PyKey::LaunchApplication2() => Key::LaunchApplication2,
            PyKey::LaunchCalendar() => Key::LaunchCalendar,
            PyKey::LaunchContacts() => Key::LaunchContacts,
            PyKey::LaunchMail() => Key::LaunchMail,
            PyKey::LaunchMediaPlayer() => Key::LaunchMediaPlayer,
            PyKey::LaunchMusicPlayer() => Key::LaunchMusicPlayer,
            PyKey::LaunchPhone() => Key::LaunchPhone,
            PyKey::LaunchScreenSaver() => Key::LaunchScreenSaver,
            PyKey::LaunchSpreadsheet() => Key::LaunchSpreadsheet,
            PyKey::LaunchWebBrowser() => Key::LaunchWebBrowser,
            PyKey::LaunchWebCam() => Key::LaunchWebCam,
            PyKey::LaunchWordProcessor() => Key::LaunchWordProcessor,
            PyKey::BrowserBack() => Key::BrowserBack,
            PyKey::BrowserFavorites() => Key::BrowserFavorites,
            PyKey::BrowserForward() => Key::BrowserForward,
            PyKey::BrowserHome() => Key::BrowserHome,
            PyKey::BrowserRefresh() => Key::BrowserRefresh,
            PyKey::BrowserSearch() => Key::BrowserSearch,
            PyKey::BrowserStop() => Key::BrowserStop,
            PyKey::AppSwitch() => Key::AppSwitch,
            PyKey::Call() => Key::Call,
            PyKey::Camera() => Key::Camera,
            PyKey::CameraFocus() => Key::CameraFocus,
            PyKey::EndCall() => Key::EndCall,
            PyKey::GoBack() => Key::GoBack,
            PyKey::GoHome() => Key::GoHome,
            PyKey::HeadsetHook() => Key::HeadsetHook,
            PyKey::LastNumberRedial() => Key::LastNumberRedial,
            PyKey::Notification() => Key::Notification,
            PyKey::MannerMode() => Key::MannerMode,
            PyKey::VoiceDial() => Key::VoiceDial,
            PyKey::TV() => Key::TV,
            PyKey::TV3DMode() => Key::TV3DMode,
            PyKey::TVAntennaCable() => Key::TVAntennaCable,
            PyKey::TVAudioDescription() => Key::TVAudioDescription,
            PyKey::TVAudioDescriptionMixDown() => Key::TVAudioDescriptionMixDown,
            PyKey::TVAudioDescriptionMixUp() => Key::TVAudioDescriptionMixUp,
            PyKey::TVContentsMenu() => Key::TVContentsMenu,
            PyKey::TVDataService() => Key::TVDataService,
            PyKey::TVInput() => Key::TVInput,
            PyKey::TVInputComponent1() => Key::TVInputComponent1,
            PyKey::TVInputComponent2() => Key::TVInputComponent2,
            PyKey::TVInputComposite1() => Key::TVInputComposite1,
            PyKey::TVInputComposite2() => Key::TVInputComposite2,
            PyKey::TVInputHDMI1() => Key::TVInputHDMI1,
            PyKey::TVInputHDMI2() => Key::TVInputHDMI2,
            PyKey::TVInputHDMI3() => Key::TVInputHDMI3,
            PyKey::TVInputHDMI4() => Key::TVInputHDMI4,
            PyKey::TVInputVGA1() => Key::TVInputVGA1,
            PyKey::TVMediaContext() => Key::TVMediaContext,
            PyKey::TVNetwork() => Key::TVNetwork,
            PyKey::TVNumberEntry() => Key::TVNumberEntry,
            PyKey::TVPower() => Key::TVPower,
            PyKey::TVRadioService() => Key::TVRadioService,
            PyKey::TVSatellite() => Key::TVSatellite,
            PyKey::TVSatelliteBS() => Key::TVSatelliteBS,
            PyKey::TVSatelliteCS() => Key::TVSatelliteCS,
            PyKey::TVSatelliteToggle() => Key::TVSatelliteToggle,
            PyKey::TVTerrestrialAnalog() => Key::TVTerrestrialAnalog,
            PyKey::TVTerrestrialDigital() => Key::TVTerrestrialDigital,
            PyKey::TVTimer() => Key::TVTimer,
            PyKey::AVRInput() => Key::AVRInput,
            PyKey::AVRPower() => Key::AVRPower,
            PyKey::ColorF0Red() => Key::ColorF0Red,
            PyKey::ColorF1Green() => Key::ColorF1Green,
            PyKey::ColorF2Yellow() => Key::ColorF2Yellow,
            PyKey::ColorF3Blue() => Key::ColorF3Blue,
            PyKey::ColorF4Grey() => Key::ColorF4Grey,
            PyKey::ColorF5Brown() => Key::ColorF5Brown,
            PyKey::ClosedCaptionToggle() => Key::ClosedCaptionToggle,
            PyKey::Dimmer() => Key::Dimmer,
            PyKey::DisplaySwap() => Key::DisplaySwap,
            PyKey::DVR() => Key::DVR,
            PyKey::Exit() => Key::Exit,
            PyKey::FavoriteClear0() => Key::FavoriteClear0,
            PyKey::FavoriteClear1() => Key::FavoriteClear1,
            PyKey::FavoriteClear2() => Key::FavoriteClear2,
            PyKey::FavoriteClear3() => Key::FavoriteClear3,
            PyKey::FavoriteRecall0() => Key::FavoriteRecall0,
            PyKey::FavoriteRecall1() => Key::FavoriteRecall1,
            PyKey::FavoriteRecall2() => Key::FavoriteRecall2,
            PyKey::FavoriteRecall3() => Key::FavoriteRecall3,
            PyKey::FavoriteStore0() => Key::FavoriteStore0,
            PyKey::FavoriteStore1() => Key::FavoriteStore1,
            PyKey::FavoriteStore2() => Key::FavoriteStore2,
            PyKey::FavoriteStore3() => Key::FavoriteStore3,
            PyKey::Guide() => Key::Guide,
            PyKey::GuideNextDay() => Key::GuideNextDay,
            PyKey::GuidePreviousDay() => Key::GuidePreviousDay,
            PyKey::Info() => Key::Info,
            PyKey::InstantReplay() => Key::InstantReplay,
            PyKey::Link() => Key::Link,
            PyKey::ListProgram() => Key::ListProgram,
            PyKey::LiveContent() => Key::LiveContent,
            PyKey::Lock() => Key::Lock,
            PyKey::MediaApps() => Key::MediaApps,
            PyKey::MediaAudioTrack() => Key::MediaAudioTrack,
            PyKey::MediaLast() => Key::MediaLast,
            PyKey::MediaSkipBackward() => Key::MediaSkipBackward,
            PyKey::MediaSkipForward() => Key::MediaSkipForward,
            PyKey::MediaStepBackward() => Key::MediaStepBackward,
            PyKey::MediaStepForward() => Key::MediaStepForward,
            PyKey::MediaTopMenu() => Key::MediaTopMenu,
            PyKey::NavigateIn() => Key::NavigateIn,
            PyKey::NavigateNext() => Key::NavigateNext,
            PyKey::NavigateOut() => Key::NavigateOut,
            PyKey::NavigatePrevious() => Key::NavigatePrevious,
            PyKey::NextFavoriteChannel() => Key::NextFavoriteChannel,
            PyKey::NextUserProfile() => Key::NextUserProfile,
            PyKey::OnDemand() => Key::OnDemand,
            PyKey::Pairing() => Key::Pairing,
            PyKey::PinPDown() => Key::PinPDown,
            PyKey::PinPMove() => Key::PinPMove,
            PyKey::PinPToggle() => Key::PinPToggle,
            PyKey::PinPUp() => Key::PinPUp,
            PyKey::PlaySpeedDown() => Key::PlaySpeedDown,
            PyKey::PlaySpeedReset() => Key::PlaySpeedReset,
            PyKey::PlaySpeedUp() => Key::PlaySpeedUp,
            PyKey::RandomToggle() => Key::RandomToggle,
            PyKey::RcLowBattery() => Key::RcLowBattery,
            PyKey::RecordSpeedNext() => Key::RecordSpeedNext,
            PyKey::RfBypass() => Key::RfBypass,
            PyKey::ScanChannelsToggle() => Key::ScanChannelsToggle,
            PyKey::ScreenModeNext() => Key::ScreenModeNext,
            PyKey::Settings() => Key::Settings,
            PyKey::SplitScreenToggle() => Key::SplitScreenToggle,
            PyKey::STBInput() => Key::STBInput,
            PyKey::STBPower() => Key::STBPower,
            PyKey::Subtitle() => Key::Subtitle,
            PyKey::Teletext() => Key::Teletext,
            PyKey::VideoModeNext() => Key::VideoModeNext,
            PyKey::Wink() => Key::Wink,
            PyKey::ZoomToggle() => Key::ZoomToggle,
            PyKey::F1() => Key::F1,
            PyKey::F2() => Key::F2,
            PyKey::F3() => Key::F3,
            PyKey::F4() => Key::F4,
            PyKey::F5() => Key::F5,
            PyKey::F6() => Key::F6,
            PyKey::F7() => Key::F7,
            PyKey::F8() => Key::F8,
            PyKey::F9() => Key::F9,
            PyKey::F10() => Key::F10,
            PyKey::F11() => Key::F11,
            PyKey::F12() => Key::F12,
            PyKey::F13() => Key::F13,
            PyKey::F14() => Key::F14,
            PyKey::F15() => Key::F15,
            PyKey::F16() => Key::F16,
            PyKey::F17() => Key::F17,
            PyKey::F18() => Key::F18,
            PyKey::F19() => Key::F19,
            PyKey::F20() => Key::F20,
            PyKey::F21() => Key::F21,
            PyKey::F22() => Key::F22,
            PyKey::F23() => Key::F23,
            PyKey::F24() => Key::F24,
            PyKey::F25() => Key::F25,
            PyKey::F26() => Key::F26,
            PyKey::F27() => Key::F27,
            PyKey::F28() => Key::F28,
            PyKey::F29() => Key::F29,
            PyKey::F30() => Key::F30,
            PyKey::F31() => Key::F31,
            PyKey::F32() => Key::F32,
            PyKey::F33() => Key::F33,
            PyKey::F34() => Key::F34,
            PyKey::F35() => Key::F35,
        }
    }
}

#[pymethods]
impl PyKey {
    fn __repr__(&self) -> String {
        match self {
            Self::Character { value } => format!("Key.Character({value:?})"),
            Self::Unidentified { value } => {
                format!("Key.Unidentified({})", value.__repr__())
            }
            Self::Dead { value: Some(value) } => format!("Key.Dead({value:?})"),
            Self::Dead { value: None } => "Key.Dead(None)".to_string(),
            value => format!("Key.{value:?}").replace("()", ""),
        }
    }

    fn __copy__(&self) -> Self {
        self.clone()
    }

    fn __deepcopy__(&self, _memo: &Bound<'_, PyAny>) -> Self {
        self.clone()
    }
}
