pub mod accumulated_mouse;
pub mod axis;
pub mod button_input;
pub mod button_state;
pub mod gamepad;
pub mod gamepad_axis;
pub mod gamepad_button;
pub mod gamepad_event;
pub mod gamepad_events;
pub mod gamepad_input;
pub mod gamepad_rumble_intensity;
pub mod gamepad_rumble_request;
pub mod gamepad_settings;
pub mod gesture_events;
pub mod key_code;
pub mod keyboard_events;
pub mod keyboard_input;
pub mod keyboard_input_ext;
pub mod mouse_button;
pub mod mouse_events;
pub mod mouse_input;
pub mod mouse_scroll_unit;
pub mod plugin;
pub mod touch_input;
pub mod touch_phase;
pub mod touches;

pub use accumulated_mouse::{PyAccumulatedMouseMotion, PyAccumulatedMouseScroll};
pub use axis::PyAxis;
pub use button_input::PyButtonInput;
pub use button_state::PyButtonState;
pub use gamepad::PyGamepad;
pub use gamepad_axis::PyGamepadAxis;
pub use gamepad_button::PyGamepadButton;
pub use gamepad_event::PyGamepadEvent;
pub use gamepad_events::{
    PyGamepadAxisChanged, PyGamepadButtonChanged, PyGamepadButtonStateChanged, PyGamepadConnection,
};
pub use gamepad_input::PyGamepadInput;
pub use gamepad_rumble_intensity::PyGamepadRumbleIntensity;
pub use gamepad_rumble_request::PyGamepadRumbleRequest;
pub use gamepad_settings::{
    PyAxisSettings, PyButtonAxisSettings, PyButtonSettings, PyGamepadSettings,
};
pub use gesture_events::{PyDoubleTapGesture, PyPanGesture, PyPinchGesture, PyRotationGesture};
pub use key_code::PyKeyCode;
pub use keyboard_events::PyKeyboardFocusLost;
pub use keyboard_input::PyKeyboardInput;
pub use keyboard_input_ext::PyKeyboardInputExt;
pub use mouse_button::PyMouseButton;
pub use mouse_events::{PyMouseButtonInput, PyMouseMotion, PyMouseWheel};
pub use mouse_input::PyMouseInput;
pub use mouse_scroll_unit::PyMouseScrollUnit;
pub use plugin::PyInputPlugin;
use pyo3::prelude::*;
pub use touch_input::PyTouchInput;
pub use touch_phase::PyTouchPhase;
pub use touches::{PyTouch, PyTouches};
pub fn add_module(parent: &Bound<'_, PyModule>) -> PyResult<()> {
    let m = PyModule::new(parent.py(), "input")?;
    m.add_class::<PyInputPlugin>()?;
    m.add_class::<PyAxis>()?;
    m.add_class::<PyButtonInput>()?;
    m.add_class::<PyButtonState>()?;
    m.add_class::<PyGamepad>()?;
    m.add_class::<PyGamepadAxis>()?;
    m.add_class::<PyGamepadButton>()?;
    m.add_class::<PyGamepadInput>()?;
    m.add_class::<PyGamepadRumbleIntensity>()?;
    m.add_class::<PyGamepadRumbleRequest>()?;
    m.add_class::<PyGamepadSettings>()?;
    m.add_class::<PyButtonSettings>()?;
    m.add_class::<PyAxisSettings>()?;
    m.add_class::<PyButtonAxisSettings>()?;
    m.add_class::<PyKeyCode>()?;
    m.add_class::<PyMouseButton>()?;
    m.add_class::<PyMouseButtonInput>()?;
    m.add_class::<PyMouseInput>()?;
    m.add_class::<PyMouseMotion>()?;
    m.add_class::<PyMouseScrollUnit>()?;
    m.add_class::<PyMouseWheel>()?;
    m.add_class::<PyTouchInput>()?;
    m.add_class::<PyTouchPhase>()?;

    m.add_class::<PyGamepadButtonChanged>()?;
    m.add_class::<PyGamepadAxisChanged>()?;
    m.add_class::<PyGamepadConnection>()?;
    m.add_class::<PyGamepadButtonStateChanged>()?;
    m.add_class::<PyPinchGesture>()?;
    m.add_class::<PyRotationGesture>()?;
    m.add_class::<PyDoubleTapGesture>()?;
    m.add_class::<PyPanGesture>()?;
    m.add_class::<PyKeyboardFocusLost>()?;
    m.add_class::<PyAccumulatedMouseMotion>()?;
    m.add_class::<PyAccumulatedMouseScroll>()?;
    m.add_class::<PyGamepadEvent>()?;
    m.add_class::<PyKeyboardInput>()?;
    m.add_class::<PyTouch>()?;
    m.add_class::<PyTouches>()?;
    parent.add_submodule(&m)
}
