[package]
name = "pybevy_post_process"
version = "0.2.1"
edition = "2024"
description = "Post-process types for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
numpy = { workspace = true }
pyo3 = { workspace = true, features = ["macros"] }
pybevy_color = { workspace = true }
pybevy_core = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_math = { workspace = true }

[dependencies.bevy]
workspace = true
features = ["bevy_post_process"]
