[package]
name = "pybevy_window"
version = "0.3.0"
edition = "2024"
description = "Window components for PyBevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/pybevy/pybevy"
homepage = "https://pybevy.com"

[dependencies]
pyo3 = { workspace = true, features = ["macros"] }
pybevy_core = { workspace = true }
pybevy_input = { workspace = true }
pybevy_macros = { workspace = true }
pybevy_math = { workspace = true }
numpy = { workspace = true }

[dependencies.bevy]
workspace = true
features = ["bevy_window", "std"]

[lints]
workspace = true
